### PR TITLE
[SW-1199, SW-1204] Latest Tx widget - problem with btc transaction

### LINKED ISSUE #2423: Show all types of Btc Tx between accounts in the Latest Tx widget
https://aeternity-blockchain.atlassian.net/browse/SW-1199

**Bug Description**

If btc transactions occur between accounts in the same wallet, then the user will see only sent transactions, or received if the page is refreshed.

**Expected result**

We need to show both received and sent btc Tx inside the wallet for different accounts. Since we do it for ae tokens.

**Steps to reproduce**
1. Send btc from acc 2 to acc1 or vice versa 
2. Check Latest Tx widget 

**Environment selector**

- Firefox
- MacOS
- Web wallet

Image
Image
Image
https://github.com/superhero-com/superhero-wallet/assets/147718725/9b7e7e7e-04ca-4c02-bc1e-e8aa22d0f999

### LINKED ISSUE #2424: Latest transaction widget disappearing on the wallet dashboard (BTC txs not fetched properly)
[fix/latest-tx](https://github.com/aeternity/superhero-wallet/tree/fix/latest-tx)

https://aeternity-blockchain.atlassian.net/browse/SW-1204

**Describe the bug**
Fetching the Bitcoin transactions for the widget works only from time to time. Screen recording is attached.
The latest transactions widget shows at first when the wallet dashboard is loaded. Then the current account details modal is opened. When it’s closed (and user goes back to Dashboard) the widget has disappeared. Probably because the BTC transaction is not being properly fetched.
Same behavior is observed if user refresh the browser tab. 

**Expected result**
Transactions are properly fetched and shown in Transactions list and in the Latest transactions widget. 

**Steps to reproduce**
1. Open Superhero wallet Dashboard. Use account with only BTC transactions.
2. Observe the Latest transactions widget behavior if opening and closing the current account details screen.
3. Observe the Latest transactions widget behavior when refreshing the browser tab.
Screen recording is attached.

**Environment selector**
- Chrome
- Extension
- Windows

Image
Image
https://github.com/superhero-com/superhero-wallet/assets/147718725/4ba8c022-dae6-4250-89e7-35a6aa71278d
https://github.com/superhero-com/superhero-wallet/assets/147718725/be032fe5-9a31-482b-93a7-f55ba42b4afa
https://github.com/superhero-com/superhero-wallet/assets/147718725/adbd2a1d-3a0f-446d-b3fb-d5120d2c2dbd

### PR DESCRIPTION
**Pull request by konradodo**
fixes #2423,
fixes #2424

### CODE REVIEW

File: src/composables/transactionList.ts [hunk 1]
```diff
@@ -327,6 +344,7 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
 
   watch(transactions, (value) => {
     setLocalStorageItem([TRANSACTIONS_LOCAL_STORAGE_KEY, nodeNetworkId.value!], value);
+    console.log(transactions);
```
Comment (subhod-i) [inline src/composables/transactionList.ts:221]: Console

**Review by subhod-i — COMMENTED** [review]
I would redefine the latest transaction widget in an all-new design. 

Here is a simple proposal.

1. The latest transaction component will never make any REST API calls.
2. The transaction list computes all loaded, pending, and new incoming transactions. It may make REST calls in a watcher or maybe when there is a balance change.
3. The latest transaction would then just compute the list and sort it based on time.

File: src/composables/transactionList.ts [hunk 2]
```diff
@@ -1,29 +1,31 @@
...
-import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
 
+import { ProtocolAdapterFactory } from '@/lib/ProtocolAdapterFactory';
+// TS-ignore
+import { useAeTransactionList } from '@/protocols/aeternity/composables/aeTransactionsList';
 import { useAccounts } from './accounts';
-import { useMiddleware } from './middleware';
 import { useAeSdk } from './aeSdk';
 
+const btcAdapter = ProtocolAdapterFactory.getAdapter(PROTOCOL_BITCOIN);
```
Comment (peronczyk) [inline src/composables/transactionList.ts:27]: The goal for us is to avoid any use of data, variables, components related to one specific protocol in the global scope. This composable is global, so what it should is:
1. Get currently used protocols
2. Get adapters for those protocols
3. Run the correct adapter method to fetch the transactions.

So the adapters should have correct methods for all cases.

File: src/composables/transactionList.ts [hunk 3]
```diff
@@ -1,29 +1,31 @@
...
-  fetchJson,
   getLocalStorageItem,
   setLocalStorageItem,
 } from '@/utils';
-import JsonBig from '@/lib/json-big';
-import { AEX9_TRANSFER_EVENT } from '@/protocols/aeternity/config';
-import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
 
+import { ProtocolAdapterFactory } from '@/lib/ProtocolAdapterFactory';
+// TS-ignore
```
Comment (peronczyk) [inline src/composables/transactionList.ts:22]: What is the reason for this?

File: src/composables/transactionList.ts [hunk 4]
```diff
@@ -129,160 +128,52 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
-      fetchPendingTransactions(address),
-      fetchTipWithdrawnTransactions(address, recent),
-    ]);
-
-    const lastPendingTransaction = pendingTransactions?.[pendingTransactions.length - 1];
-    if (lastPendingTransaction?.type === AEX9_TRANSFER_EVENT) {
-      const middleware = await getMiddleware();
-      pendingTransactions[pendingTransactions.length - 1] = (
-        await middleware.getTx(lastPendingTransaction.payload.txHash)
+    if (protocol === PROTOCOL_AETERNITY) {
```
Comment (peronczyk) [inline src/composables/transactionList.ts:141]: As mentioned before - we should not have any protocol specific logic in the global scope.

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/composables/transactionList.ts [hunk 5]
```diff
@@ -329,15 +253,59 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
 
+  async function updateAllTransactions() {
+    await Promise.all(accounts.value.map((account) => fetchTransactions(
+      account.address,
+      account.protocol,
+    )));
+  }
+  const { onNetworkChange } = createNetworkWatcher();
+  const { balancesTotal } = useBalances({ store });
+  const tokens = computed(() => store.state.fungibleTokens.tokens);
```
Comment (konradodo) [inline src/composables/transactionList.ts:264]: i will move its on the top of file

**Review by subhod-i — COMMENTED** [review]
I like the new overall approach. We can prepare this PR to be merged.

File: src/composables/transactionList.ts [hunk 6]
```diff
@@ -129,149 +127,75 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
+    const response = await adapter.fetchTransactions(
+      address,
+      transactionState.nextPageUrl,
+    );
+
+    const pendingTransactions = response.pendingTransactions?.filter(
+      (transaction: ITransaction) => !transactionState.pending[nodeNetworkId.value!]?.find(
+        (tx) => tx?.hash === transaction?.hash,
+      ),
+    ).map((transaction: ITransaction) => ({ ...transaction, pending: true })) || [];
```
Comment (pstachel) [inline src/composables/transactionList.ts:153]: I'd suggest better formatting to have chained methods on new lines
```
... = response.pendingTransactions
?.filter(...)
.map(...)
```

File: src/composables/transactionList.ts [hunk 7]
```diff
@@ -129,149 +127,75 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
+
     let preparedTransactions = [
       ...pendingTransactions,
-      ...regularTransactions,
+      ...response.regularTransactions,
     ]
       .filter(({ type }) => !type?.startsWith('Internal'))
       .map((transaction) => ({
-        ...(transaction.payload || transaction),
+        ...((transaction as any).payload || transaction),
```
Comment (pstachel) [inline src/composables/transactionList.ts:172]: don't we have a type for transaction? If you'd type it in the map you won't need typing below

File: src/composables/transactionList.ts [hunk 8]
```diff
@@ -329,15 +253,59 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
     setLocalStorageItem([TRANSACTIONS_LOCAL_STORAGE_KEY, nodeNetworkId.value!], value);
   }, { deep: true, immediate: true });
 
+  async function updateAllTransactions() {
+    await Promise.all(accounts.value.map((account) => fetchTransactions(
+      account.address,
+      account.protocol,
+    )));
+  }
+  const { onNetworkChange } = createNetworkWatcher();
```
Comment (pstachel) [inline src/composables/transactionList.ts:262]:
```suggestion
  }
  
  const { onNetworkChange } = createNetworkWatcher();
```

File: src/protocols/aeternity/helpers/actions.ts [hunk 9]
```diff
@@ -0,0 +1,124 @@
+import { Encoded, Tag } from '@aeternity/aepp-sdk';
+import { ITransaction } from '@/types';
+import JsonBig from '@/lib/json-big';
+import { fetchJson } from '@/utils';
+import { useAeSdk } from '@/composables/aeSdk';
+import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
+import { AeSdkSuperhero } from '@/protocols/aeternity/libs/AeSdkSuperhero';
+import { useStore } from 'vuex';
+import { useMiddleware } from '@/composables/middleware';
```
Comment (pstachel) [inline src/protocols/aeternity/helpers/actions.ts:9]: please organize the imports properly:
1) libs
2) types
3) other js/ts files

File: src/protocols/aeternity/helpers/actions.ts [hunk 10]
```diff
@@ -0,0 +1,124 @@
...
+  const {
+    fetchFromMiddlewareCamelCased,
+  } = useMiddleware();
+
+  const url = ([null, ''].includes(nextPageUrl))
+    ? `/v2/accounts/${address}/activities?limit=${limit}`
+    : nextPageUrl!;
+
+  try {
+    const x = await fetchFromMiddlewareCamelCased(url);
```
Comment (pstachel) [inline src/protocols/aeternity/helpers/actions.ts:25]: Please use meaningful names

File: src/protocols/aeternity/helpers/actions.ts [hunk 11]
```diff
@@ -0,0 +1,124 @@
...
+
+export async function fetchAeTransactions(
+  limit: number,
+  address: Encoded.AccountAddress,
+  nextPageUrl: string | null,
+) {
+  const store = useStore();
+  const { getAeSdk } = useAeSdk({ store });
+  const sdk = await getAeSdk(); // Ensure the `nodeNetworkId` is established
+  if (typeof nextPageUrl !== 'string') {
```
Comment (pstachel) [inline src/protocols/aeternity/helpers/actions.ts:101]:
```suggestion
  const sdk = await getAeSdk(); // Ensure the `nodeNetworkId` is established
  
  if (typeof nextPageUrl !== 'string') {
```

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 12]
```diff
@@ -194,8 +197,12 @@ export class AeternityAdapter extends BaseProtocolAdapter {
...
   }
 
-  async fetchTransactions(): Promise<any> {
-    // TODO
+  async fetchTransactions(address:string, nextPageParams:string | null): Promise<any> {
+    return fetchAeTransactions(
+      TXS_PER_PAGE,
+        address as Encoded.AccountAddress,
+        nextPageParams,
+    );
```
Comment (pstachel) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:205]:
```suggestion
    return fetchAeTransactions(
      TXS_PER_PAGE,
      address as Encoded.AccountAddress,
      nextPageParams,
    );
```

File: src/protocols/aeternity/helpers/actions.ts [hunk 13]
```diff
@@ -0,0 +1,124 @@
...
+    const { getAeSdk } = useAeSdk({ store });
+    const { aeActiveNetworkSettings } = useAeNetworkSettings();
+    await getAeSdk();
+
+    const response = await fetchJson(
+      `${aeActiveNetworkSettings.value.backendUrl}/cache/events/?address=${address}&event=TipWithdrawn${recent ? '&limit=5' : ''}`,
+    );
+    if (response.message) {
+      return [];
+    }
```
Comment (pstachel) [inline src/protocols/aeternity/helpers/actions.ts:65]: Isn't it a mistake?

Comment (konradodo) [reply src/protocols/aeternity/helpers/actions.ts:66]: no, this is correct if (message -> error)

**Comment by Liubov-crypto** [comment]
it seems that accounts discovery is broken

File: src/types/index.ts [hunk 14]
```diff
@@ -407,6 +407,7 @@ export interface ITransaction {
   protocol?: Protocol;
   rawTx?: any; // TODO find type
   tipUrl?: string;
+  type?: string
```
Comment (subhod-i) [inline src/types/index.ts:410]:
```suggestion
  type?: string;
```

File: src/types/index.ts [hunk 15]
```diff
@@ -658,3 +659,10 @@ export interface IWalletInfo {
   origin: any;
   type: any;
 }
+
+export interface IFetchTransactionResult {
+  regularTransactions: ITransaction[],
+  pendingTransactions?: any[], // TODO preparing types for PendingTransaction
+  tipWithdrawnTransactions?: ITransaction[]
+  nextPageParams: string | null
+}
```
Comment (subhod-i) [inline src/types/index.ts:668]:
```suggestion
export interface IFetchTransactionResult {
  regularTransactions: ITransaction[];
  pendingTransactions?: any[]; // TODO preparing types for PendingTransaction
  tipWithdrawnTransactions?: ITransaction[];
  nextPageParams: string | null;
}
```

**Review by subhod-i — APPROVED** [review]
Added two comments, REST looks good.

File: src/types/index.ts [hunk 16]
```diff
@@ -407,6 +407,7 @@ export interface ITransaction {
   protocol?: Protocol;
   rawTx?: any; // TODO find type
   tipUrl?: string;
+  type?: string;
```
Comment (peronczyk) [inline src/types/index.ts:410]: Please add some context to this. Possible values or some description.

File: src/protocols/aeternity/helpers/actions.ts [hunk 17]
```diff
@@ -0,0 +1,127 @@
...
+import { AeSdkSuperhero } from '@/protocols/aeternity/libs/AeSdkSuperhero';
+
+async function fetchTransactionsFromMiddleware(
+  address: Encoded.AccountAddress,
+  nextPageUrl: string | null,
+  limit: number,
+) {
+  const {
+    fetchFromMiddlewareCamelCased,
+  } = useMiddleware();
```
Comment (peronczyk) [inline src/protocols/aeternity/helpers/actions.ts:18]: The role for utilities is to be a small functions that does simple things. So the general flow is that larger (more complex) entities imports smaller ones. Not the opposite. So here smaller one is using bigger one - I consider this as antipattern.

File: src/store/modules/accounts/hdWallet.js [hunk 18]
```diff
@@ -34,6 +34,7 @@ export default {
         .getAdapter(PROTOCOL_AETERNITY) // Discover only aeternity accounts for now
         .discoverAccounts(wallet);
 
+      console.log({ numberOfAccounts });
```
Comment (peronczyk) [inline src/store/modules/accounts/hdWallet.js:37]: Leftover

File: src/protocols/aeternity/views/TransactionDetails.vue [hunk 19]
```diff
@@ -92,6 +91,7 @@ import DetailsItem from '@/popup/components/DetailsItem.vue';
 import LinkButton from '@/popup/components/LinkButton.vue';
 import Truncate from '@/popup/components/Truncate.vue';
 import CopyText from '@/popup/components/CopyText.vue';
+import { useTransactionList } from '@/composables/transactionList';
```
Comment (peronczyk) [inline src/protocols/aeternity/views/TransactionDetails.vue:94]: Please add this import to existing composable imports.

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 20]
```diff
@@ -194,8 +198,15 @@ export class AeternityAdapter extends BaseProtocolAdapter {
     // TODO
   }
 
-  async fetchTransactions(): Promise<any> {
-    // TODO
+  async fetchTransactions(
+    address:string,
+    nextPageParams:string | null,
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:203]: Missing spaces after colons.

Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:203]: I suggest to return `undefined` instead of `null` so it can be typed with the use of question mark:
```
nextPageParams?: string
```

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 21]
```diff
@@ -176,7 +178,9 @@ export class AeternityAdapter extends BaseProtocolAdapter {
               this.getHdWalletAccountFromMnemonicSeed(seed, index).publicKey,
             )),
         );
+        console.log({ isAccountUsedArray });
       } catch (e) {
+        console.log(e);
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:183]: Ekhm

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/protocols/aeternity/components/TransferReview.vue [hunk 22]
```diff
@@ -107,6 +106,7 @@ import TransferReviewBase from '@/popup/components/TransferSend/TransferReviewBa
 import AccountItem from '@/popup/components/AccountItem.vue';
 import DetailsItem from '@/popup/components/DetailsItem.vue';
 import TokenAmount from '@/popup/components/TokenAmount.vue';
+import { useTransactionList } from '@/composables/transactionList';
```
Comment (peronczyk) [inline src/protocols/aeternity/components/TransferReview.vue:109]: Please add this to existing composables import.

File: src/popup/pages/AccountDetailsMultisigTransactions.vue [hunk 23]
```diff
@@ -24,17 +24,17 @@ import {
...
   useConnection,
   useMultisigAccounts,
   usePendingMultisigTransaction,
   useTransactionAndTokenFilter,
-  useTransactionList,
   useUi,
   useViewport,
 } from '@/composables';
 
+import { useTransactionList } from '@/composables/transactionList';
```
Comment (peronczyk) [inline src/popup/pages/AccountDetailsMultisigTransactions.vue:37]: Please add this to existing composables import.

File: src/popup/pages/Retip.vue [hunk 24]
```diff
@@ -88,12 +88,12 @@ import {
   useAccounts,
   useTippingContracts,
   useAeSdk,
-  useTransactionList,
 } from '@/composables';
 import { AE_COIN_PRECISION, AE_CONTRACT_ID } from '@/protocols/aeternity/config';
 
 import { ProtocolAdapterFactory } from '@/lib/ProtocolAdapterFactory';
 import { PROTOCOL_AETERNITY } from '@/constants';
+import { useTransactionList } from '@/composables/transactionList';
```
Comment (peronczyk) [inline src/popup/pages/Retip.vue:96]: Please add this to existing composables import.

File: src/protocols/BaseProtocolAdapter.ts [hunk 25]
```diff
@@ -77,8 +77,8 @@ export abstract class BaseProtocolAdapter {
 
   abstract fetchTransactions(
     address: string,
-    lastTxId?: string,
-  ): Promise<any>;
+    nextPageParams: string | null,
```
Comment (peronczyk) [inline src/protocols/BaseProtocolAdapter.ts:80]: I suggest to use `undefined` instead of `null` so this can by typed with the use of question mark.

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/popup/components/Modals/AccountCreate.vue [hunk 26]
```diff
@@ -74,7 +74,7 @@ export default defineComponent({
 
         case PROTOCOL_BITCOIN:
           await store.dispatch('accounts/hdWallet/create', {
-            isRestored: false,
+            isnpRestored: false,
```
Comment (peronczyk) [inline src/popup/components/Modals/AccountCreate.vue:77]: `isnp`? Looks like a mistake.

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 27]
```diff
@@ -176,7 +178,9 @@ export class AeternityAdapter extends BaseProtocolAdapter {
               this.getHdWalletAccountFromMnemonicSeed(seed, index).publicKey,
             )),
         );
+        console.log({ isAccountUsedArray });
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:181]: Ekhm

File: src/protocols/aeternity/libs/AeternityAdapter.ts (hunk 21 above)
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:183]: :)

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 28]
```diff
@@ -194,8 +198,15 @@ export class AeternityAdapter extends BaseProtocolAdapter {
...
-    // TODO
+  async fetchTransactions(
+    address:string,
+    nextPageParams:string | null,
+  ): Promise<IFetchTransactionResult> {
+    return fetchAeTransactions(
+      TXS_PER_PAGE,
+      address as Encoded.AccountAddress,
+      nextPageParams,
+    );
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:209]: Why not put all the logic of the `fetchAeTransactions` inside of the method itself?

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/protocols/bitcoin/libs/BitcoinAdapter.ts [hunk 29]
```diff
@@ -161,14 +163,24 @@ export class BitcoinAdapter extends BaseProtocolAdapter {
     return lastNotEmptyIdx;
   }
 
-  async fetchTransactions(address: string, lastTxId?: string) {
+  async fetchTransactions(
+    address: string,
+    lastTxId: string | null,
```
Comment (peronczyk) [inline src/protocols/bitcoin/libs/BitcoinAdapter.ts:168]:
```suggestion
    lastTxId?: string,
```

File: src/types/index.ts [hunk 30]
```diff
@@ -658,3 +659,10 @@ export interface IWalletInfo {
   origin: any;
   type: any;
 }
+
+export interface IFetchTransactionResult {
+  regularTransactions: ITransaction[];
+  pendingTransactions?: any[]; // TODO preparing types for PendingTransaction
+  tipWithdrawnTransactions?: ITransaction[];
+  nextPageParams: string | null;
```
Comment (peronczyk) [inline src/types/index.ts:667]:
```suggestion
  nextPageParams?: string;
```

File: src/types/index.ts [hunk 31]
```diff
@@ -658,3 +659,10 @@ export interface IWalletInfo {
   origin: any;
   type: any;
 }
+
+export interface IFetchTransactionResult {
+  regularTransactions: ITransaction[];
+  pendingTransactions?: any[]; // TODO preparing types for PendingTransaction
```
Comment (peronczyk) [inline src/types/index.ts:665]:
```suggestion
  pendingTransactions?: any[]; // TODO prepare types for PendingTransaction
```

File: src/composables/transactionList.ts [hunk 32]
```diff
@@ -1,30 +1,33 @@
...
   setLocalStorageItem,
 } from '@/utils';
-import JsonBig from '@/lib/json-big';
-import { AEX9_TRANSFER_EVENT } from '@/protocols/aeternity/config';
-import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
 
+import { ProtocolAdapterFactory } from '@/lib/ProtocolAdapterFactory';
+import { AE_MDW_TO_NODE_APPROX_DELAY_TIME, AEX9_TRANSFER_EVENT } from '@/protocols/aeternity/config';
+import { useMiddleware } from '@/composables/middleware';
+import { isEqual, orderBy, uniqBy } from 'lodash-es';
```
Comment (peronczyk) [inline src/composables/transactionList.ts:23]: This line should be one of the first in this file. I don;t understand why you changed the order.

File: src/composables/transactionList.ts [hunk 33]
```diff
@@ -1,30 +1,33 @@
...
+import { useBalances } from '@/composables/balances';
+import { createNetworkWatcher } from '@/composables/networks';
```
Comment (peronczyk) [inline src/composables/transactionList.ts:25]: I don;t understand why you changed the paths here. This is local import from the same directory. Please revert this change.

File: src/composables/transactionList.ts [hunk 34]
```diff
@@ -1,30 +1,33 @@
...
   getLocalStorageItem,
   setLocalStorageItem,
 } from '@/utils';
-import JsonBig from '@/lib/json-big';
-import { AEX9_TRANSFER_EVENT } from '@/protocols/aeternity/config';
-import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
 
+import { ProtocolAdapterFactory } from '@/lib/ProtocolAdapterFactory';
+import { AE_MDW_TO_NODE_APPROX_DELAY_TIME, AEX9_TRANSFER_EVENT } from '@/protocols/aeternity/config';
+import { useMiddleware } from '@/composables/middleware';
```
Comment (peronczyk) [inline src/composables/transactionList.ts:22]: I don;t understand why you changed the paths here. This is local import from the same directory. Please revert this change.

File: src/composables/transactionList.ts [hunk 35]
```diff
@@ -58,18 +61,17 @@ function updateAccountTransaction(address: Encoded.AccountAddress, transaction:
   }
 }
 
-const setTransactionsNextPage = (address: Encoded.AccountAddress, url: string) => {
+const setTransactionsNextPage = (address: string, url: string | null) => {
```
Comment (peronczyk) [inline src/composables/transactionList.ts:64]:
```suggestion
const setTransactionsNextPage = (address: string, url?: string) => {
```

File: src/composables/transactionList.ts [hunk 36]
```diff
@@ -58,18 +61,17 @@ function updateAccountTransaction(address: Encoded.AccountAddress, transaction:
...
 export function useTransactionList({ store }: IDefaultComposableOptions) {
-  const { aeActiveNetworkSettings } = useAeNetworkSettings();
   const { nodeNetworkId, getAeSdk } = useAeSdk({ store });
   const { isLoggedIn, accounts } = useAccounts({ store });
-  const {
-    fetchFromMiddlewareCamelCased,
-    getMiddleware,
-  } = useMiddleware();
+  const { getMiddleware } = useMiddleware();
+  const { onNetworkChange } = createNetworkWatcher();
```
Comment (peronczyk) [inline src/composables/transactionList.ts:72]: Creation of the network watcher should be done before defining the composable. Please see how it's used in other files.

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/protocols/aeternity/helpers/actions.ts
Comment (peronczyk) [inline src/protocols/aeternity/helpers/actions.ts:1]: I think the contents of this file should be moved into Aeternity Adapter.

File: src/composables/transactionList.ts (hunk 35 above)
Comment (konradodo) [reply src/composables/transactionList.ts:64]: null is returned from api if we get last page.

File: src/composables/transactionList.ts (hunk 34 above)
Comment (konradodo) [reply src/composables/transactionList.ts:22]: this is related to problem with load adapter. You found solution and you wrote to me how import useMiddleware

File: src/composables/transactionList.ts (hunk 33 above)
Comment (konradodo) [reply src/composables/transactionList.ts:25]: Dependency cycle detected.

File: src/protocols/BaseProtocolAdapter.ts (hunk 25 above)
Comment (konradodo) [reply src/protocols/BaseProtocolAdapter.ts:80]: null is returned from api when we get the latest page

Comment (peronczyk) [reply src/protocols/BaseProtocolAdapter.ts:80]: OK

File: src/composables/transactionList.ts (hunk 34 above)
Comment (peronczyk) [reply src/composables/transactionList.ts:23]: It's not about splitting the composables into separate imports as this was done this way before. My component referst to the fact that you changed the import paths for files that are imported from the same directory. Before it was `./middleware` and you changed it to `@/composables/middleware` which makes no sense here.

File: src/composables/transactionList.ts (hunk 33 above)
Comment (peronczyk) [reply src/composables/transactionList.ts:25]: Its not related to dependency cycle. It's a matter of the path:
```suggestion
import { useBalances } from './balances';
import { createNetworkWatcher } from './networks';
```

File: src/store/plugins/names.js [hunk 37]
```diff
@@ -116,7 +112,10 @@ export default (store) => {
         commit,
       }) {
         commit('setAreNamesFetching', true);
-        const fetchPendingNameClaimTransactions = (address) => fetchPendingTransactions(address)
+        const { fetchPendingTransactions } = ProtocolAdapterFactory.getAdapter(PROTOCOL_AETERNITY);
+        const fetchPendingNameClaimTransactions = (address) => (
+          fetchPendingTransactions(address)
+        )
```
Comment (peronczyk) [inline src/store/plugins/names.js:118]: It makes no sense to create separate function that is a shortcut to another. This can be removed and in the following code just use:
```
adapter.fetchPendingTransactions(address);
```

File: src/store/plugins/names.js [hunk 38]
```diff
@@ -116,7 +112,10 @@ export default (store) => {
         commit,
       }) {
         commit('setAreNamesFetching', true);
-        const fetchPendingNameClaimTransactions = (address) => fetchPendingTransactions(address)
+        const { fetchPendingTransactions } = ProtocolAdapterFactory.getAdapter(PROTOCOL_AETERNITY);
```
Comment (peronczyk) [inline src/store/plugins/names.js:115]: In my opinion picking methods from a class by destructuring it is rather bad pattern. I suggest to save the adapter instance to constant:
```
const adapter = ProtocolAdapterFactory.getAdapter(PROTOCOL_AETERNITY);
```
and then use methods on it:
```
adapter.someMethod()
```

File: src/protocols/bitcoin/views/AccountDetailsTransactions.vue [hunk 39]
```diff
@@ -101,7 +96,7 @@ export default defineComponent({
 
     return {
       isOnline,
-      transactions,
+      transactions: loadedTransactionList,
```
Comment (peronczyk) [inline src/protocols/bitcoin/views/AccountDetailsTransactions.vue:99]: By following the naming pattern for two next lines: `transactionsLatest` and `transactionsMore` the name used in this line should be: `transactionsLoaded`.

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 40]
```diff
@@ -169,8 +174,121 @@ export class AeternityAdapter extends BaseProtocolAdapter {
...
+        nextPageParams: next,
+      };
+    } catch (error) {
+      return {};
+    }
+  }
+
+  async fetchPendingTransactions(
+    address: string,
+    sdk: AeSdkSuperhero,
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:204]: I think this method should follow the same pattern as other methods, so the `sdk` should be retrieved in the body of the function instead of passed as the argument.

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 41]
```diff
@@ -34,6 +34,11 @@ import {
 } from '@/protocols/aeternity/config';
 import { AeScan } from '@/protocols/aeternity/libs/AeScan';
 import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
+import { useMiddleware } from '@/composables/middleware';
+import { AeSdkSuperhero } from '@/protocols/aeternity/libs/AeSdkSuperhero';
+import JsonBig from '@/lib/json-big';
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:39]: Please put this before all local imports.

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 42]
```diff
@@ -3,7 +3,7 @@ import {
   encode,
   Encoded,
   Encoding,
-  getHdWalletAccountFromSeed,
+  getHdWalletAccountFromSeed, Tag,
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:6]: Please split this line.

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 43]
```diff
@@ -169,8 +174,121 @@ export class AeternityAdapter extends BaseProtocolAdapter {
...
+        claim: true,
+      }));
+
+      return tipWithdrawnTransactions;
+    } catch (error) {
+      return [];
+    }
+  }
+
+  async fetchTransactions(
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:261]: Please add `override` keyword before this declaration.

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/store/plugins/names.js [hunk 44]
```diff
@@ -116,19 +112,19 @@ export default (store) => {
...
-            })));
+        const adapter = ProtocolAdapterFactory.getAdapter(PROTOCOL_AETERNITY);
 
         const middleware = await getMiddleware();
         const names = await Promise.all(
           aeAccounts.value.map(({ address }) => Promise.all([
-            fetchPendingNameClaimTransactions(address),
+            adapter.fetchPendingTransactions(address)
+              .then((transactions) => transactions
+                .filter(({ tx: { type } }) => type === 'NameClaimTx')
```
Comment (peronczyk) [inline src/store/plugins/names.js:122]: In my opinion mixing `Promise.all` with `.then` and filtering in one block of code is rather bad practice. It makes the code hard to read.
I suggest to first fetch the data and make the operations on existing constant.

File: src/composables/transactionList.ts [hunk 45]
```diff
@@ -265,15 +191,16 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
-    tipWithdrawnTransactions.forEach((f) => {
+    response.tipWithdrawnTransactions?.forEach((f) => {
       if (f.microTime
-        && (
-          minMicroTime < f.microTime
-          || (preparedTransactions.length === 0 && minMicroTime > f.microTime))
+          && (
+            minMicroTime < f.microTime
+            || (preparedTransactions.length === 0 && minMicroTime > f.microTime))
       ) {
```
Comment (peronczyk) [inline src/composables/transactionList.ts:199]: If any of the lines is split I suggest to split all of them:
```suggestion
if (
  f.microTime
  && (
    minMicroTime < f.microTime
    || (preparedTransactions.length === 0 && minMicroTime > f.microTime)
  )
) {
```

File: src/composables/transactionList.ts [hunk 46]
```diff
@@ -129,122 +131,46 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
-
   async function fetchTransactions(
-    limit: number,
-    recent: boolean,
     address: Encoded.AccountAddress,
+    protocol?: Protocol,
   ): Promise<ITransaction[]> {
-    await getAeSdk(); // Ensure the `nodeNetworkId` is established
-
+    await getAeSdk();
```
Comment (peronczyk) [inline src/composables/transactionList.ts:138]: Why did you remove the comment? It explained why we wait for the SDK without actually using it.

File: src/composables/transactionList.ts [hunk 47]
```diff
@@ -129,122 +131,46 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
+      ?.filter((transaction: ITransaction) => !transactionState.pending[nodeNetworkId.value!]?.find(
+        (tx) => tx?.hash === transaction?.hash,
+      ))
+      .map((transaction) => ({ ...transaction, pending: true })) || [];
+
+    const lastPendingTransaction = pendingTransactions?.[pendingTransactions.length - 1];
     // DEX transaction is represented in 3 objects, only last one should be used
     // this condition checking edge case when not all 3 objects in one chunk
-    if (lastRegularTransaction?.type === AEX9_TRANSFER_EVENT) {
+    if (lastPendingTransaction?.type === AEX9_TRANSFER_EVENT) {
```
Comment (peronczyk) [inline src/composables/transactionList.ts:162]: I think this logic should be moved into the `AeternityAdapter` where we fetch the pending transactions.

File: src/protocols/bitcoin/views/AccountDetailsTransactions.vue [hunk 48]
```diff
@@ -101,7 +96,7 @@ export default defineComponent({
 
     return {
       isOnline,
-      transactions,
+      transactions: transactionsLoaded,
```
Comment (peronczyk) [inline src/protocols/bitcoin/views/AccountDetailsTransactions.vue:99]: Instead of renaming the returned const name please update the template to use `transactionsLoaded`.

File: src/composables/transactionList.ts (hunk 47 above)
Comment (peronczyk) [reply src/composables/transactionList.ts:162]: After having some conversation I see it's not possible for now. Resolving...

File: src/composables/transactionList.ts (hunk 35 above)
Comment (peronczyk) [inline src/composables/transactionList.ts:64]: Please use regular function to match the convention we use.

File: src/composables/transactionList.ts [hunk 49]
```diff
@@ -58,18 +61,17 @@ function updateAccountTransaction(address: Encoded.AccountAddress, transaction:
...
 }
 
-const setTransactionsNextPage = (address: Encoded.AccountAddress, url: string) => {
+const setTransactionsNextPage = (address: string, url: string | null) => {
   transactions.value[address].nextPageUrl = url;
 };
 
 export function useTransactionList({ store }: IDefaultComposableOptions) {
-  const { aeActiveNetworkSettings } = useAeNetworkSettings();
+  const { onNetworkChange } = createNetworkWatcher();
```
Comment (peronczyk) [inline src/composables/transactionList.ts:69]: `createNetworkWatcher` should be initialized before the actual composable scope.

**Review by CedrikNikita — CHANGES_REQUESTED** [review]
This PR loads the next page of transactions on the `Dashboard` until all transactions have been loaded. This results in many calculations associated with retrieving and formatting data that are not required by the screen and user actions.
image

File: src/composables/loading.ts [hunk 50]
```diff
@@ -0,0 +1,24 @@
...
+
+  async function callback(
+    func: (...args: any[]) => Promise<any>,
+    onError?: <T = any>(e: T) => void,
+  ) {
+    try {
+      isLoading.value = true;
+      await func();
+    } catch (e) {
+      onError?.(e);
```
Comment (pstachel) [inline src/composables/loading.ts:14]: shouldn't we have default handling in case onError function isn't passed?

File: src/composables/transactionList.ts [hunk 51]
```diff
@@ -151,9 +151,8 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
     );
 
     const pendingTransactions = response.pendingTransactions
-      ?.filter((transaction: ITransaction) => !transactionState.pending[nodeNetworkId.value!]?.find(
-        (tx) => tx?.hash === transaction?.hash,
-      ))
+      ?.filter((transaction: ITransaction) => (
+        transactionState.localPendingTransaction?.hash !== transaction?.hash))
```
Comment (pstachel) [inline src/composables/transactionList.ts:155]: Format those lines

File: src/composables/transactionList.ts [hunk 52]
```diff
@@ -192,26 +191,25 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
     response.tipWithdrawnTransactions?.forEach((f) => {
-      if (f.microTime
-          && (
-            minMicroTime < f.microTime
-            || (preparedTransactions.length === 0 && minMicroTime > f.microTime))
+      if (
+        f.microTime
+        && (
+          minMicroTime < f.microTime
+          || (preparedTransactions.length === 0 && minMicroTime > f.microTime))
```
Comment (pstachel) [inline src/composables/transactionList.ts:198]: formatting

File: src/composables/transactionList.ts [hunk 53]
```diff
@@ -234,10 +232,28 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
     return preparedTransactions;
   }
 
+  async function loadMoreTransactions(
+    address: Encoded.AccountAddress,
+  ) {
```
Comment (pstachel) [inline src/composables/transactionList.ts:237]:
```suggestion
async function loadMoreTransactions(address: Encoded.AccountAddress)
```

File: src/composables/transactionList.ts [hunk 54]
```diff
@@ -234,10 +232,28 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
+    return fetchTransactions(
+      address,
+      false,
+    );
+  }
+
+  async function fetchLatestTransactions(
+    address: Encoded.AccountAddress,
+  ) {
```
Comment (pstachel) [inline src/composables/transactionList.ts:246]:
```suggestion
async function fetchLatestTransactions(address: Encoded.AccountAddress)
```

File: src/composables/transactionList.ts [hunk 55]
```diff
@@ -279,9 +294,10 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
    * we are fetching the transactions only if the total balance of the accounts changes.
    */
   watch(
-    balances,
+    accountsTotalBalance,
     (val, oldVal) => {
       if (val !== oldVal) {
+        console.log('balances', val, oldVal);
```
Comment (pstachel) [inline src/composables/transactionList.ts:300]: Should be removed

File: src/popup/pages/AccountDetailsMultisigTransactions.vue [hunk 56]
```diff
@@ -24,15 +24,15 @@ import {
...
+import { executeAndSetInterval } from '@/utils';
 import {
   useConnection,
   useMultisigAccounts,
   usePendingMultisigTransaction,
   useTransactionAndTokenFilter,
   useUi,
   useViewport,
-  useTransactionList,
+  useTransactionList, useLoading,
```
Comment (pstachel) [inline src/popup/pages/AccountDetailsMultisigTransactions.vue:35]: split this line

File: src/popup/pages/FungibleTokens/TokenTransactions.vue [hunk 57]
```diff
@@ -2,18 +2,23 @@
...
-    :loading="loading"
+    :loading="isLoading"
     @load-more="loadMore()"
   />
 </template>
 
 <script lang="ts">
 import {
-  computed, defineComponent, ref, onMounted,
+  computed, defineComponent, onMounted,
```
Comment (pstachel) [inline src/popup/pages/FungibleTokens/TokenTransactions.vue:12]: please split this line

File: src/protocols/aeternity/views/AccountDetailsTransactions.vue [hunk 58]
```diff
@@ -25,14 +25,13 @@ import {
 import { useStore } from 'vuex';
 
 import type { ICommonTransaction } from '@/types';
-import { PROTOCOL_AETERNITY } from '@/constants';
+import { executeAndSetInterval } from '@/utils';
 import {
   useAccounts,
-  useConnection,
+  useConnection, useLoading,
```
Comment (pstachel) [inline src/protocols/aeternity/views/AccountDetailsTransactions.vue:31]: new line

File: src/protocols/bitcoin/views/AccountDetailsTransactions.vue [hunk 59]
```diff
@@ -27,12 +27,13 @@ import { useStore } from 'vuex';
 import type { ITransaction, ICommonTransaction } from '@/types';
 import {
   useAccounts,
-  useConnection,
+  useConnection, useLoading,
```
Comment (pstachel) [inline src/protocols/bitcoin/views/AccountDetailsTransactions.vue:30]: new line

**Review by pstachel — CHANGES_REQUESTED** [review]

File: src/composables/loading.ts
Comment (peronczyk) [inline src/composables/loading.ts:1]: I understand that this composable is to replace repetitive code. But in my opinion repetitive code is not always bad. Especially if it's easy to understand. So I don't agree we should use this composable. Having `isLoading` ref and `try...catch` block is really straightforward thing.

File: src/composables/transactionList.ts [hunk 60]
```diff
@@ -58,26 +65,28 @@ function updateAccountTransaction(address: Encoded.AccountAddress, transaction:
...
-  const { isLoggedIn, accounts } = useAccounts();
-  const {
-    fetchFromMiddlewareCamelCased,
-    getMiddleware,
-  } = useMiddleware();
+  const { isLoggedIn, accounts, getAccountByAddress } = useAccounts();
+  const { getMiddleware } = useMiddleware();
+
+  const { accountsTotalBalance } = useBalances();
+  const tokens = computed(() => store.state.fungibleTokens.tokens);
```
Comment (pstachel) [inline src/composables/transactionList.ts:78]:
```suggestion
  const { getMiddleware } = useMiddleware();
  const { accountsTotalBalance } = useBalances();
  
  const tokens = computed(() => store.state.fungibleTokens.tokens);
```

File: src/store/plugins/names.js [hunk 61]
```diff
@@ -115,19 +111,24 @@ export default (store) => {
...
       }) {
         commit('setAreNamesFetching', true);
-        const fetchPendingNameClaimTransactions = (address) => fetchPendingTransactions(address)
-          .then((transactions) => transactions
-            .filter(({ tx: { type } }) => type === 'NameClaimTx')
+        const adapter = ProtocolAdapterFactory.getAdapter(PROTOCOL_AETERNITY);
+
+        const middleware = await getMiddleware();
+
+        async function fetchPendingsTransactions(address) {
```
Comment (pstachel) [inline src/store/plugins/names.js:118]:
```suggestion
        async function fetchPendingTransactions(address) {
```

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 62]
```diff
@@ -34,6 +38,9 @@ import {
 } from '@/protocols/aeternity/config';
 import { AeScan } from '@/protocols/aeternity/libs/AeScan';
 import { useAeNetworkSettings } from '@/protocols/aeternity/composables';
+import { useMiddleware } from '@/composables/middleware';
+import { ITransaction } from '@/types';
```
Comment (pstachel) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:42]: This import is used twice

File: src/protocols/BaseProtocolAdapter.ts [hunk 63]
```diff
@@ -75,10 +75,14 @@ export abstract class BaseProtocolAdapter {
 
   abstract getTransactionByHash(hash: string): Promise<any>
 
+  abstract fetchPendingTransactions(
+    address: string
+  ): Promise<any>
```
Comment (pstachel) [inline src/protocols/BaseProtocolAdapter.ts:80]: Do pending transactions have different type than ITransaction?

File: src/composables/transactionList.ts [hunk 64]
```diff
@@ -340,15 +284,56 @@ export function useTransactionList({ store }: IDefaultComposableOptions) {
...
+  );
+
+  onNetworkChange(() => {
+    updateAllTransactions();
+  });
+
+  (async () => {
+    if (!isInitialized) {
+      isInitialized = true;
+      await updateAllTransactions();
```
Comment (pstachel) [inline src/composables/transactionList.ts:324]: Do you need to await it here?

Comment (konradodo) [reply src/composables/transactionList.ts:324]: yes, for proper set isInitialized

**Review by peronczyk — APPROVED** [review]

File: src/protocols/BaseProtocolAdapter.ts [hunk 65]
```diff
@@ -4,10 +4,10 @@ import type {
   ICoin,
   IHdWalletAccount,
   INetworkProtocolSettings,
+  IFetchTransactionResult,
   MarketData,
-  NetworkTypeDefault,
+  NetworkTypeDefault, ITransaction,
```
Comment (pstachel) [inline src/protocols/BaseProtocolAdapter.ts:9]:
```suggestion
  NetworkTypeDefault, 
  ITransaction,
```

File: src/protocols/bitcoin/views/AccountDetailsTransactions.vue [hunk 66]
```diff
@@ -118,15 +127,19 @@ export default defineComponent({
...
+        }
       }, 10000);
     });
 
     onUnmounted(() => {
-      if (pollingInterval) {
-        clearInterval(pollingInterval);
+      if (polling) {
+        clearInterval(polling);
       }
```
Comment (pstachel) [inline src/protocols/bitcoin/views/AccountDetailsTransactions.vue:141]: Why won't you use `createPollingBasedOnMountedComponents`?

File: tests/e2e/integration/other.js [hunk 67]
```diff
@@ -17,7 +17,7 @@ describe('Tests cases not connected to specific page', () => {
   it('(not) redirects to last visited routes', () => {
     [
       { path: '/notifications', redirect: false },
-      { path: '/account-details/names', redirect: true },
+      // { path: '/account-details/names', redirect: true },
```
Comment (peronczyk) [inline tests/e2e/integration/other.js:20]: I think this test needst to be uncommented.

File: src/protocols/bitcoin/libs/BitcoinAdapter.ts [hunk 68]
```diff
@@ -166,14 +168,29 @@ export class BitcoinAdapter extends BaseProtocolAdapter {
     );
   }
 
-  async fetchTransactions(address: string, lastTxId?: string) {
+  override async fetchPendingTransactions() {
+    // TODO if needed
+    return [];
+  }
```
Comment (peronczyk) [inline src/protocols/bitcoin/libs/BitcoinAdapter.ts:174]: Can be removed?

File: src/protocols/aeternity/views/AccountDetailsTransactions.vue [hunk 69]
```diff
@@ -1,194 +1,31 @@
...
-        <MessageOffline
-          v-else
-          class="offline-message"
-          :text="$t('modals.accountDetails.transactionsNotAvailable')"
-        />
-      </div>
-    </IonContent>
+  <IonPage>
+    <AccountDetailsTransactionsBase
+      v-bind="$attrs"
```
Comment (peronczyk) [inline src/protocols/aeternity/views/AccountDetailsTransactions.vue:4]: I strongly rrecommend to avoid passing all attributes to child components.

File: src/protocols/bitcoin/views/AccountDetailsTransactions.vue [hunk 70]
```diff
@@ -1,170 +1,31 @@
...
-        <MessageOffline
-          v-else
-          class="offline-message"
-          :text="$t('modals.accountDetails.transactionsNotAvailable')"
-        />
-      </div>
-    </IonContent>
+  <IonPage>
+    <AccountDetailsTransactionsBase
+      v-bind="$attrs"
```
Comment (peronczyk) [inline src/protocols/bitcoin/views/AccountDetailsTransactions.vue:4]: I strongly recommend to not pass all the attributes to the child component.

**Review by peronczyk — CHANGES_REQUESTED** [review]

**Review by peronczyk — APPROVED** [review]
