### PR TITLE
fix: switch networks correctly

### LINKED ISSUE #2740: After adding a custom network and deleting it in console will be a lot of errors
**Describe the bug**
I've added a custom network, after delete it and switched to mainnet, found these issues in console:
тестнет

джсон

**To Reproduce**
1. Go to ETH/BTC 
2. Click on Settings and add custom network
3. Remove custom network and switch to mainnet

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 122

**Additional context**
Reproducible on eth support branch.

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2740

### CODE REVIEW

File: src/popup/components/NetworkRow.vue [hunk 1]
```diff
@@ -82,9 +82,9 @@ export default defineComponent({
   },
   emits: {
     // eslint-disable-next-line @typescript-eslint/no-unused-vars
-    selectNetwork: (name: string) => undefined,
+    selectNetwork: (name: string) => true,
```
Comment (CedrikNikita) [inline src/popup/components/NetworkRow.vue:85]: This fixes warnings that we have.
```
[Vue warn]: Invalid event arguments: event validation failed for event "selectNetwork".
```

**Comment by Liubov-crypto** [comment]
fixed, LGTM

**Review by martinkaintas — APPROVED** [review]
