### PR TITLE
fix(ethereum): validate token amount when asset is predefined

### LINKED ISSUE #2612: There is no validation for amount on ERC-20 token details page
**Describe the bug**
If I'm trying to send ERC-20 tokens from token details page there will be no amount validation on Send modal field

**To Reproduce**
1. Open erc-20 token details page
2. Enter recipients address
3. Enter amount 

**Expected behavior**
should work normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF 
 - Version 121

**Additional context**
Reproducible on eth support branch. 

Image

Image

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2612

### CODE REVIEW

File: src/protocols/ethereum/components/TransferSendForm.vue [hunk 1]
```diff
@@ -133,13 +134,11 @@ export default defineComponent({
       maxPriorityFeePerGas,
       updateFeeList,
     } = useEthFeeCalculation();
-    const { getProtocolAvailableTokens } = useFungibleTokens();
-
-    const ethTokensAvailable = computed(() => getProtocolAvailableTokens(PROTOCOLS.ethereum));
+    const { accountAssets } = useAccountAssetsList({ searchTerm: ref('') });
```
Comment (martinkaintas) [inline src/protocols/ethereum/components/TransferSendForm.vue:137]:
```suggestion
    const { accountAssets } = useAccountAssetsList();
```
I don't see why we need this

**Review by martinkaintas — CHANGES_REQUESTED** [review]

**Review by martinkaintas — APPROVED** [review]
LGTM

**Comment by Liubov-crypto** [comment]
LGTM
