### PR TITLE
fix: show auction bids

### LINKED ISSUE #2651: AENS Bid history page is broken
https://aeternity-blockchain.atlassian.net/browse/SW-1257

**Describe the bug**

On Bid history page are not displaying the full history of bids. Example: https://develop.wallet.z52da5wt.xyz/account-details/names/auctions/coolname.chain/history 

 

**Steps to reproduce**
1. Choose a name
2. Check Bid history page

**Environment selector**

Chrome
Extension
Firefox
MacOS
iOS
Web wallet

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2651

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
I can see Bid history. 

On testnet it shows bid history with names from mainnet. Other names from testnet are not shown according to issue with backend:

nam

**Comment by Liubov-crypto** [comment]
Fixed, LGTM. 

The issue with showing names from mainet on testnet should be fixed separately.

**Review by martinkaintas — APPROVED** [review]

File: src/popup/pages/Names/Auction.vue [hunk 1]
```diff
@@ -73,19 +75,27 @@ export default defineComponent({
...
+        const [auctionInfo, accountActivities] = await Promise.all([
+          middleware.getName(props.name),
+          // TODO: show more than 100 bids
+          middleware.getAccountActivities(nameId, { limit: 100 }),
+        ]);
+
+        const { auctionEnd } = auctionInfo.info;
+
+        const bids = accountActivities.data
+          .filter(({ type }: any) => type === 'NameClaimEvent')
```
Comment (peronczyk) [inline src/popup/pages/Names/Auction.vue:88]: I suggest to store the `NameClaimEvent` as a const.
