### PR TITLE
fix: transaction list is displaying partly

### LINKED ISSUE #2563: Header is missing after sending Tx within the wallet
**Describe the bug**
if user send tokens from the 1st account to the 2nd one inside the wallet, and then open the transaction details, the header disappears

**To Reproduce**
1. Send ae coin from 1st acc to 2nd acc
2. Check tx details
3. Go back

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 119

**Additional context**
reproducible on the dev branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/92562a07-54ac-449d-b11e-5cc0a7ae9357

### LINKED ISSUE #2572: Screen with transaction list and assets list is displaying partly
**Describe the bug**
Screen with transaction list and assets list is displaying partly, not all information is visible

**To Reproduce**
1. Go to transaction list and assets list 
2. See error

**Expected behavior**
Should be fully visible. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device:  iPhone13
 - OS:  iOS 17.1.2

**Additional context**

https://github.com/superhero-com/superhero-wallet/assets/69896204/faf04428-c8a7-465b-9ac9-1484d6e510df

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2572 
closes #2563

As much as I hate using this `ionicLifecycleStatus` prop, it is the best way to achieve what we're trying to do. Which is to calculate the tabs-height after the page transition has played. `onIonViewDidEnter` fires at exactly that moment but isn't directly available to the `AccountDetailsBase` component thus we pass it as a prop.
Using the timeout didn't always work correctly because depending on the user's machine the animation can take longer or even not play at all (e.g. animations are disabled on FF or user visits the page directly)

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
In general the transaction list view has been fixed. 
But for the some reason I can't see all my assets ( I see only 4 from 25: https://aescan.io/accounts/ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k?type=tokens). And DEX related transactions are displaying as Token A/ Token B, there is no "true" token name.

assets
tok

**Comment by Liubov-crypto** [comment]
The issue with assets list is also present on dev, on dev eth branch and even on product
I think there is an issue with mainnet , I got 400 error

File: src/popup/components/AccountDetailsBase.vue [hunk 1]
```diff
@@ -157,16 +160,22 @@ export default defineComponent({
       },
     );
 
+    watch(
+      () => props.ionicLifecycleStatus,
+      (value) => {
+        if (value === 'didEnter') {
```
Comment (peronczyk) [inline src/popup/components/AccountDetailsBase.vue:166]: What if the value is different? Maybe we need to unobserve?

File: src/protocols/aeternity/views/AccountDetails.vue [hunk 2]
```diff
@@ -58,6 +61,7 @@ import CreditCardIcon from '@/icons/credit-card.svg?vue-component';
 import SwapIcon from '@/icons/swap.svg?vue-component';
 import FaucetIcon from '@/icons/faucet.svg?vue-component';
 import GlobeSmallIcon from '@/icons/globe-small.svg?vue-component';
+import { IonicLifecycleStatus } from '@/types';
```
Comment (peronczyk) [inline src/protocols/aeternity/views/AccountDetails.vue:64]: Please put this line above local imports.

File: src/popup/components/AccountDetailsBase.vue (hunk 1 above)
Comment (martinkaintas) [reply src/popup/components/AccountDetailsBase.vue:166]: `ResizeObservers` are supposed to disconnect when the element is removed. But for clarity we can call `disconnect()`

**Comment by Liubov-crypto** [comment]
https://github.com/superhero-com/superhero-wallet/issues/2563 - has been fixed. 

https://github.com/superhero-com/superhero-wallet/issues/2572 - it seems to be fixed too. But if I'm opening console and then close it I will see my list after only partly. Is this view could be caused by console opening? 


https://github.com/superhero-com/superhero-wallet/assets/69896204/449adb3b-cb2f-4a49-8d46-23039eb8417e

p.s. multisig accounts are not visible, I think this is related to old URLs.

**Comment by martinkaintas** [comment]
It is related to the opening of the console because it interferes with the way we calculate the height :/
Is this something we want to fix?

**Comment by Liubov-crypto** [comment]
> It is related to the opening of the console because it interferes with the way we calculate the height :/ Is this something we want to fix?

I don't think that someone from regular users will open console to check there errors :) 

if other reviewers are ok with this, I'm also ok :)

**Comment by CedrikNikita** [comment]
Currently in the #2659, the `IonPage` is added in `AccountDetailsTransactionsBase`, to solve the same problem on hooks is not accessible. Can this be fixed the same way? What in general do you think of that approach?

**Comment by martinkaintas** [comment]
> Currently in the #2659, the `IonPage` is added in `AccountDetailsTransactionsBase`, to solve the same problem on hooks is not accessible. Can this be fixed the same way? What in general do you think of that approach?

In the mentioned PR [this line](https://github.com/superhero-com/superhero-wallet/pull/2659/files#diff-1ed85de4c375d07db0f12a185bde23caf8979423a0add30a4624b2bd3bf9fdcaL151) was also changed so that `AccountDetailsTranactionsBase` is directly mapped with the router. Which was done to satisfy this constraint by [Ionic](https://ionicframework.com/docs/vue/lifecycle):

> These lifecycles are only called on components directly mapped by a router

Removing the protocol specific `AccountDetailsTransactions` files was possible because they were just using `AccountDetailsTranactionsBase` without any other additions.

In the case of `AccountDetails` we cannot move all the logic and the different UIs that we want to the Base component

File: src/protocols/aeternity/views/AccountDetails.vue [hunk 3]
```diff
@@ -1,7 +1,10 @@
 <template>
   <IonPage>
     <IonContent class="account-ion-content">
-      <AccountDetailsBase class="account-details">
+      <AccountDetailsBase
+        class="account-details"
+        :ionic-lifecycle-status="ionicLifecycleStatus"
```
Comment (peronczyk) [inline src/protocols/aeternity/views/AccountDetails.vue:6]: Instead of passing the prop deeper and deeper just use `v-if` in one of the parents and display/hide the element to force it to render again when the ionic lifecycle changes?

**Review by peronczyk — CHANGES_REQUESTED** [review]

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
LGTM in general. 

But I got again issue with console opening: 

https://github.com/superhero-com/superhero-wallet/assets/69896204/e0031d42-d655-4910-98e5-3ed58aed556c
