### PR TITLE
fix: eth max button should stay on

### LINKED ISSUE #2909: Max amount button is stop working if ETH balance is less than fee
**Describe the bug**
Max amount button is stop working if ETH balance is less than fee

**To Reproduce**
1. Go to Send ETH, your ETH balance should be lower than fee
2. Click on Max button
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, FF
 - Version 123

**Additional context**

ьфч

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2909

### CODE REVIEW

**Comment by CedrikNikita** [comment]
1. Shouldn't we introduce this behaviour to other protocols?
2. We should also show the user that the data was changed. @onvisions had some suggestions about it.

File: src/protocols/ethereum/components/TransferSendForm.vue [hunk 1]
```diff
@@ -31,12 +31,13 @@
             : {},
           enough_coin: [fee.toString(), ETH_COIN_SYMBOL],
         }"
+        @update:model-value="() => shouldUseMaxAmount = false"
```
Comment (peronczyk) [inline src/protocols/ethereum/components/TransferSendForm.vue:34]: No need to use callback:
```suggestion
        @update:model-value="shouldUseMaxAmount = false"
```

**Comment by onvisions** [comment]
@CedrikNikita @martinkaintas @peronczyk 
> 1. Shouldn't we introduce this behaviour to other protocols?
> 2. We should also show the user that the data was changed. @onvisions had some suggestions about it.

IMO
1. - Yes, we should. Consistency.
2. - if you mean the smooth "blinking" transition of updated values (I shared a video of the effect): Yes, we'd better apply it so user will visually be aware that data has changed.

**Comment by CedrikNikita** [comment]
On opening the modal.
```
TypeError: Cannot read properties of null (reading 'animate')
```

File: src/utils/common.ts [hunk 2]
```diff
@@ -502,3 +502,42 @@ export function getCleanModalOptions<T>(options: T): Omit<T, 'onCompiler' | 'onN
   delete cleanedOptions?.onNode;
   return cleanedOptions;
 }
+/**
+ * Returns animation that blinks the element with the option to call a callback
+ * in the middle of the animation (opacity 0).
+ */
+export function createBlinkAnimation(el: HTMLElement, callback?: () => void) {
```
Comment (peronczyk) [inline src/utils/common.ts:509]: I strongly suggest to use CSS instead.

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/popup/components/InputField.vue [hunk 3]
```diff
@@ -206,7 +210,20 @@ export default defineComponent({
       (val) => emit('focus-change', val),
     );
 
+    watch(
+      () => props.modelValue,
+      () => {
+        if (props.blinkOnChange) {
+          inputEl.value?.classList.add('hide');
```
Comment (peronczyk) [inline src/popup/components/InputField.vue:217]: Why using vanilla JS instead of `:class`?

Also in my opinion this block of code is not self explanatory. Why adding and removing `hide` class? Are we hiding something here?

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/popup/components/TokenAmount.vue [hunk 4]
```diff
@@ -51,13 +57,20 @@ export default defineComponent({
     dynamicSizing: Boolean,
     large: Boolean,
     small: Boolean,
+    blinkOnChange: Boolean,
   },
   setup(props) {
+    const tokenAmountEl = ref<HTMLElement>();
+    const amountRounded = ref<string|number>(0);
```
Comment (peronczyk) [inline src/popup/components/TokenAmount.vue:64]:
```suggestion
    const amountRounded = ref<string | number>(0);
```

File: src/popup/components/TokenAmount.vue [hunk 5]
```diff
@@ -71,15 +84,34 @@ export default defineComponent({
...
+      amountRounded.value = getAmountRounded();
+      amountFiat.value = getAmountFiat();
+    }
 
-    const symbolComputed = computed(() => props.symbol || adapter.coinSymbol);
+    watch(() => props.amount, () => {
+      if (!props.blinkOnChange) {
+        updateAmountValues();
+      }
+      tokenAmountEl.value?.classList.add('hide');
```
Comment (peronczyk) [inline src/popup/components/TokenAmount.vue:102]: IDEM - I suggest to not use vanilla here.

File: src/styles/global.scss [hunk 6]
```diff
@@ -319,3 +319,11 @@ hr {
...
   }
 }
+
+.blink {
+  transition: opacity 0.5s ease-in-out;
+
+  &.hide {
+    opacity: 0;
+  }
+}
```
Comment (peronczyk) [inline src/styles/global.scss:329]: In my opinion it would be better to create CSS animation and then on the component level adding only one class, e.g.: `value-changed` this way:

```
watch(<modal value>, async () => {
  valueChanged.value = true;
  await nextTick();
  valueChanged.value = false;
});
```

The style for this class would be:
```
.value-changed {
  animation: blink-animation...
}
```

(just a rough idea, not tested)

**Review by peronczyk — APPROVED** [review]
