### PR TITLE
fix(deep-link): be able to return `networkId`

### LINKED ISSUE #3359: Deeplink failes to provide networkId on connect request
**Describe the bug**

When opening the following url:

```
https://wallet.superhero.com/address?x-success=https%3A%2F%2Flocalhost%3Faddress%3D%7Baddress%7D%26networkId%3D%7BnetworkId%7D&x-cancel=https%3A%2F%2Flocalhost
```

and accepting the connection request in my browser I would expect to end up on the following url:

```
https://localhost/?address=ak_rRVV...DMAq&networkId=ae_mainnet
```

but instead i end up at

```
https://localhost/?address=ak_rRVV...DMAq&networkId=undefined
```

the major difference here being the networkId which is `undefined`

I followed the deeplink specification outlined here: https://github.com/superhero-com/superhero-wallet/blob/master/docs/deep-link-schema.md

**Additional context**

Superhero Wallet Version 2.3.0

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #3359

### CODE REVIEW

File: src/popup/pages/Address.vue [hunk 1]
```diff
@@ -35,10 +37,16 @@ export default defineComponent({
...
       try {
+        setLoaderVisible(true);
         await openModal(MODAL_CONFIRM_CONNECT, {
           access: [POPUP_CONNECT_ADDRESS_PERMISSION],
           app: app.value,
         });
+
+        /**
+         * Sdk should be initialized in order to get a current networkId.
+         */
```
Comment (peronczyk) [inline src/popup/pages/Address.vue:48]: No need to use DocBlock here.

```suggestion
        // Sdk should be initialized in order to get a current networkId.
```

File: src/popup/pages/JwtSign.vue [hunk 2]
```diff
@@ -72,6 +72,10 @@ export default defineComponent({
 
         const dataToSign = JSON.parse(payload);
 
+        /**
+         * Sdk should be initialized in order to get a current networkId.
+         */
```
Comment (peronczyk) [inline src/popup/pages/JwtSign.vue:77]: No need to use DocBlock here.

```suggestion
        // Sdk should be initialized in order to get a current networkId.
```

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
