### PR TITLE
fix: missing required param error

### LINKED ISSUE #2543: Error: missing required param "id"
**Describe the bug**
When I'm opening Coin details page, I'm getting error in console: Error: missing required param "id" 

**To Reproduce**
Steps to reproduce the behaviour:
1. Open account details page
2. Open Coin details page
3. Go back

**Expected behaviour**
Should work without errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF, Chrome
 - Version 119, 120

**Additional context**
Reproducible on dev branch. 

Image

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2543 

The error does not cause any issues, so maybe it is preferable to leave it as is than to add these checks

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
I can't get error: missing required param "id". 

But I'm observing that some transactions details are missing or broken. Idk if it's related to this pr. 



https://github.com/superhero-com/superhero-wallet/assets/69896204/4eadec9f-b00f-415b-b87c-1a19fbbf548a

File: src/popup/router/routes.ts [hunk 1]
```diff
@@ -275,8 +275,25 @@ export const routes: WalletAppRouteConfig[] = [
...
+        /**
+         * When a route is defined with a parameter
+         * and user leaves this route, vue-router will
+         * throw a "missing required param" error
+         * even though the parameter was set for the route
+         * Making the parameter optional & checking for it
+         * in the beforeEnter hook fixes the issue
+         *
+         * @see https://github.com/vuejs/router/issues/845
+         */
```
Comment (peronczyk) [inline src/popup/router/routes.ts:287]: I suggest to use full available width of 100 chars for the comment because right now it looks little bit too dense in my opinion.

**Review by peronczyk — APPROVED** [review]
