### PR TITLE
fix: correctly fix eth api limit issue

### LINKED ISSUE #2591: Reaching the ETH API call limit should not reset the list of ERC-20 tokens

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2591

### CODE REVIEW

File: src/composables/fungibleTokens.ts [hunk 1]
```diff
@@ -118,18 +118,37 @@ export function useFungibleTokens() {
...
-    const tokenBalancesFetchPromises = accounts.value.map(
-      ({ address, protocol }) => ProtocolAdapterFactory.getAdapter(protocol)
-        .fetchAccountTokenBalances(address),
+    const tokenBalancesFetchPromisesByAddress: Dictionary<Promise<ITokenBalance[] | null>> = {};
+    accounts.value.map(
+      ({ address, protocol }) => {
+        tokenBalancesFetchPromisesByAddress[address] = (
+          ProtocolAdapterFactory
+            .getAdapter(protocol).fetchAccountTokenBalances(address)
+        );
```
Comment (peronczyk) [inline src/composables/fungibleTokens.ts:127]:
```suggestion
        tokenBalancesFetchPromisesByAddress[address] = ProtocolAdapterFactory
            .getAdapter(protocol).fetchAccountTokenBalances(address);
```

**Comment by Liubov-crypto** [comment]
LGTM, tested on testnet.

**Review by CedrikNikita — APPROVED** [review]
