### PR TITLE
fix(aeternity): show pending and tip withdrawn transactions

### LINKED ISSUE #2796: Pending and Tipwithdrawn transactions are no longer present in transaction list

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2796

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
In general LGTM, I can see my pending Tx in Txs list.

**Comment by Liubov-crypto** [comment]
LGTM

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 1]
```diff
@@ -304,6 +304,8 @@ export class AeternityAdapter extends BaseProtocolAdapter {
         ...transaction,
         pending: true,
         protocol: PROTOCOLS.aeternity,
+        microTime: Date.now(),
```
Comment (martinkaintas) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:307]: Why do we need to add `microTime` to pending transactions?

Comment (CedrikNikita) [reply src/protocols/aeternity/libs/AeternityAdapter.ts:307]: This was our previous approach to show that it was done some time ago.

File: src/composables/transactionList.ts [hunk 2]
```diff
@@ -156,13 +171,20 @@ export function useTransactionList({
           return;
         }
 
+        const filteredLoadedTransactions = (state.value.transactionsLoaded as any)
+          .filter(({ claim = false, pending = false }) => !claim && !pending);
```
Comment (peronczyk) [inline src/composables/transactionList.ts:175]: There is no need to set default values for claim and pending.

**Review by peronczyk — APPROVED** [review]

File: src/protocols/aeternity/libs/AeternityAdapter.ts (hunk 1 above)
Comment (CedrikNikita) [reply src/protocols/aeternity/libs/AeternityAdapter.ts:307]: But it seems that `microTime` for the custom pending transaction is not being set :(. And the whole logic is not working.

Comment (peronczyk) [reply src/protocols/aeternity/libs/AeternityAdapter.ts:307]: So maybe this needs another fix?

Comment (CedrikNikita) [reply src/protocols/aeternity/libs/AeternityAdapter.ts:307]: Will do it within this PR.

Comment (onvisions) [reply src/protocols/aeternity/libs/AeternityAdapter.ts:307]: 1. We should display the timestamp in the Latest transactions widget on the wallet Dashboard as we currently do because this way the user can know approximately how much time the transaction is in a pending state:
Pending-3

2. We should not display the timestamp in the Transactions tab list under Account details because we have limited UI space there and because the user can access the single transaction details screen to see the exact timestamp.

3. Add the timestamp for pending transaction on the Transactions details screen in case we can get it (the transaction is initiated by the user by the currently active wallet account): 
Pending-5


@CedrikNikita what do you think?

Comment (CedrikNikita) [reply src/protocols/aeternity/libs/AeternityAdapter.ts:307]: I suggest to move last part to another ticket and apply current fix.
