### PR TITLE
fix: tip-in transaction details

### LINKED ISSUE #2438: TIP IN transactions present different data in transaction details after refreshing
https://aeternity-blockchain.atlassian.net/browse/SW-558

*Describe the bug*
Presented data changes after page refresh - transaction object fetched after refresh is lacking `amount` field

*Expected result*
Data should be the same after refreshing

*Steps to reproduce*
1. Go to TIP IN transaction from the transaction list
2. Refresh page

Image
Image

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2438

### CODE REVIEW

File: src/popup/components/TransactionTagList.vue [hunk 1]
```diff
@@ -110,7 +110,10 @@ export default defineComponent({
             ? t('transaction.dexType.pool')
             : t('common.swap'),
         );
-      } else if (props.transaction.claim) {
+      } else if (
+        props.transaction.claim
+        || innerTx.value.function === TX_FUNCTIONS.claim
```
Comment (CedrikNikita) [inline src/popup/components/TransactionTagList.vue:115]: Unfortunately, any contract can have a method named claim. This method is not completely correct.

Comment (martinkaintas) [reply src/popup/components/TransactionTagList.vue]: Correct, I've fixed this by also checking for the contract address

File: src/protocols/aeternity/views/TransactionDetails.vue [hunk 2]
```diff
@@ -319,10 +320,11 @@ export default defineComponent({
     onMounted(async () => {
       let rawTransaction = getTransactionByHash(activeAccount.value.address, hash);
 
-      if (!rawTransaction || rawTransaction.incomplete) {
+      // Claim transactions have missing data that needs to be fetched from the middleware
+      if (!rawTransaction || rawTransaction.incomplete || rawTransaction.claim) {
         const middleware = await getMiddleware();
         try {
-          rawTransaction = await middleware.getTx(hash);
+          rawTransaction = merge(rawTransaction, await middleware.getTx(hash));
```
Comment (CedrikNikita) [inline src/protocols/aeternity/views/TransactionDetails.vue:327]: Why this `merge` is needed?

File: src/protocols/aeternity/views/TransactionDetails.vue [hunk 3]
```diff
@@ -319,10 +320,11 @@ export default defineComponent({
     onMounted(async () => {
       let rawTransaction = getTransactionByHash(activeAccount.value.address, hash);
 
-      if (!rawTransaction || rawTransaction.incomplete) {
+      // Claim transactions have missing data that needs to be fetched from the middleware
+      if (!rawTransaction || rawTransaction.incomplete || rawTransaction.claim) {
```
Comment (CedrikNikita) [inline src/protocols/aeternity/views/TransactionDetails.vue:324]: Do we need to fetch `claim` transaction from the middleware, if we already fetched it from backend?

**Comment by Liubov-crypto** [comment]
Fixed, LGTM

File: src/protocols/aeternity/views/TransactionDetails.vue (hunk 3 above)
Comment (martinkaintas) [reply src/protocols/aeternity/views/TransactionDetails.vue:324]: Yes, the backend returns faulty and incomplete data

File: src/protocols/aeternity/views/TransactionDetails.vue (hunk 2 above)
Comment (martinkaintas) [reply src/protocols/aeternity/views/TransactionDetails.vue:327]: Because in the case of `claim` transactions we want to merge data coming from the backend & the middleware so that we always have the same (correct and complete) transaction.

File: src/protocols/aeternity/views/TransactionDetails.vue (hunk 3 above)
Comment (CedrikNikita) [reply src/protocols/aeternity/views/TransactionDetails.vue:324]: I see, incomplete transaction:
 - doesn't have `Gas price`
 - doesn't have `Gas used`
 - have a wrong timestamp

**Review by CedrikNikita — APPROVED** [review]
