### PR TITLE
fix: check for null microTime

### LINKED ISSUE #2655: Errors in console when send Btc
https://aeternity-blockchain.atlassian.net/browse/SW-1356

Describe the bug

I was sending Btc  in the testnet between accounts in 1 wallet and got errors in console. However Btc was sent. Reproducible on the current dev branch. 

Expected result

Steps to reproduce
1. Send Btc from 1 acc to 2 acc in the testnet
2. Check the console

Environment selector

Firefox
MacOS
Web wallet

Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2655

### CODE REVIEW

**Review by CedrikNikita — APPROVED** [review]

File: src/popup/components/TransactionListItem.vue [hunk 1]
```diff
@@ -168,7 +168,7 @@ export default defineComponent({
 
     onMounted(() => {
       timerInterval = executeAndSetInterval(() => {
-        transactionDate.value = (props.transaction)
+        transactionDate.value = (props.transaction && props.transaction.microTime)
```
Comment (CedrikNikita) [inline src/popup/components/TransactionListItem.vue:171]:
```suggestion
        transactionDate.value = (props.transaction?.microTime)
```
