### PR TITLE
fix: ionic lifecycle methods do not trigger

### LINKED ISSUE #2453: Ionic lifecycle methods are not being exeuted
Ionic lifecycle methods are not being exeuted when component is rendered through `ProtocolSpecificView.vue`

### LINKED ISSUE #2457: `onUnmountedHook` is not being called in AccountDetails tabs

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2453 
fixes #2457

### CODE REVIEW

File: src/types/index.ts [hunk 1]
```diff
@@ -131,8 +131,8 @@ export type IInputMessageRaw = string | IInputMessage;
  */
 export interface IToken {
   contractId: Encoded.ContractAddress
-    | typeof AE_CONTRACT_ID
-    | typeof BTC_CONTRACT_ID
+  | typeof AE_CONTRACT_ID
+  | typeof BTC_CONTRACT_ID
```
Comment (peronczyk) [inline src/types/index.ts:135]: Why? :O

File: src/protocols/aeternity/views/AccountDetailsTransactions.vue [hunk 2]
```diff
@@ -118,35 +121,54 @@ export default defineComponent({
...
 
-    onIonViewWillEnter(() => {
-      setScrollConf(false);
+        if (props.ionicLifecycleStatus === 'didLeave') {
+          onViewDidLeaveHandler();
+        }
+      },
+    );
+
+    onUnmounted(() => {
```
Comment (martinkaintas) [inline src/protocols/aeternity/views/AccountDetailsTransactions.vue:170]: `onUnmounted` is required because if you change tabs `onIonViewDidLeave` will be triggered but not  `onUnmounted`, but if you close the account-details with the x button only `onUnmounted` will be called and not  `onIonViewDidLeave`

**Review by CedrikNikita — CHANGES_REQUESTED** [review]
`onBeforeUnmount` in the `NameList` is not being triggered, please check other places that are running in tabs.

File: src/popup/pages/MultisigDetails.vue [hunk 3]
```diff
@@ -43,7 +43,7 @@
 
         <LinkButton
           class="explorer-link"
-          :to="activeMultisigAccountExplorerUrl"
+          :to="activeMultisigAccountExplorerUrl!"
```
Comment (CedrikNikita) [inline src/popup/pages/MultisigDetails.vue:46]:
```suggestion
          :to="activeMultisigAccountExplorerUrl"
```

**Review by CedrikNikita — APPROVED** [review]
