### PR TITLE
fix: estimate gas limit for erc20 transfers

### LINKED ISSUE #2971: Can’t send max erc-20
**Describe the bug**

 Can’t send max erc-20 

**To Reproduce**
1. Go to ETH account
2. Click on SEnd modal
3. Try to send max of ERC-20

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome, safari, ff
 - Version 123

**Additional context**
reproducible on dev branch

Image

Image

this issue is reproducible not for all ERC-20 tokens, only for some of them: 

https://sepolia.etherscan.io/address/0x779877A7B0D9E8603169DdbD7836e478b4624789

https://sepolia.etherscan.io/address/0xcf185f2F3Fe19D82bFdcee59E3330FD7ba5f27ce

### LINKED ISSUE #3010: The total sum for ERC-20 tokens is displaying as sum of ERC-20 plus ETH fee
**Describe the bug**
I was sending 0.0001 WETH , but see it as 0.0002 (there is a fee paid in eth)

**To Reproduce**
1. Go to ETH acc
2. Send erc-20 tokens
3. Check tx details

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser : chrome, safari
 - Version: 123 

**Additional context**
Reproducible on dev branch. 

https://github.com/superhero-com/superhero-wallet/assets/69896204/9c836b56-f4c2-414d-8d7c-8df1d17f0571

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2971 
closes #3010

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
the issue still remains:

tt
ff

**Comment by Liubov-crypto** [comment]
In general it's working. I can send max amount all my ERC-20 tokens and ETH. I would like to check it once again when new SDK version will be applied.

File: src/protocols/ethereum/components/TransferReview.vue [hunk 1]
```diff
@@ -102,11 +102,10 @@ export default defineComponent({
       loading.value = true;
       let actionResult;
       const lastActiveEthAccount = getLastActiveProtocolAccount(PROTOCOLS.ethereum);
-
       try {
         if (!isSelectedAssetEthCoin.value) {
           actionResult = await ethAdapter.transferToken?.(
-            Number(amount),
```
Comment (martinkaintas) [inline src/protocols/ethereum/components/TransferReview.vue:109]: This could force the amount to be rounded which means that it could happen that user was trying to send `1.5 LINK` when he only had `1.4999999999999 LINK`

File: src/protocols/BaseProtocolAdapter.ts [hunk 2]
```diff
@@ -119,7 +119,7 @@ export abstract class BaseProtocolAdapter {
   fetchAccountTokenBalances?(address: AccountAddress): Promise<ITokenBalance[] | null>;
 
   transferToken?(
-    amount: number,
+    amount: number | string,
```
Comment (peronczyk) [inline src/protocols/BaseProtocolAdapter.ts:122]: Maybe we could try to use only the `string` to avoid having uncertainty?

File: src/protocols/ethereum/helpers/index.ts [hunk 3]
```diff
@@ -1,9 +1,14 @@
...
 import { getBlock, getTransaction } from 'web3-eth';
+import Contract from 'web3-eth-contract';
 import BigNumber from 'bignumber.js';
+
 import { AccountAddress, ITransaction } from '@/types';
 import { PROTOCOLS } from '@/constants';
-import { ETH_CONTRACT_ID } from '../config';
+import { bigIntToHex } from 'web3-eth-accounts';
+import { ERC20_ABI, ETH_CONTRACT_ID } from '../config';
+import { useEthNetworkSettings } from '../composables/ethNetworkSettings';
```
Comment (peronczyk) [inline src/protocols/ethereum/helpers/index.ts:11]: Helper functions should not import composables as it breaks the hierarchy:
Constants -> Utils -> Libs -> Composables -> Components

**Review by peronczyk — CHANGES_REQUESTED** [review]

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
In general it's working, but could be some edge cases. 

For example: 

I got this issue when tried to send Link token one by one:
1- i sent 0.1 link
2 - was trying to sent max link in a while and got an issue 

I think this is because the previous tx was in pending status and the balance was not updated properly after sent 1st tx:

link
errr

I have question about WETH: 
is this total sum correct? 
i was sending 0.0001 WETH , but see it as 0.0002 (there is a fee paid in eth) 


https://github.com/superhero-com/superhero-wallet/assets/69896204/5a45e157-c735-4470-b803-90f00d706dbf

**Comment by Liubov-crypto** [comment]
The second issue has been fixed, LGTM. 

For the first one I've registered a separate issue.
