### PR TITLE
fix(aeternity): show correct allowance transaction info

### LINKED ISSUE #3391: Approved use of token is showing wrong in Tx details page
**Describe the bug**
Approved use of token is showing wrong in Tx details page.

**To Reproduce**
1. Try to sell some custom token
2. Click on approve modal
3. check details
4. Approved use of token will show 0.00 ae amount instead of amount of token that user want to sell

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser:  chrome
 - Version 130

**Additional context**
reproducible on dev branch 

https://testnet.aescan.io/transactions/th_sqLnYAAmGs6NNtH9UKTYNotHNL95JseSSx3ufX5bZDA2yqaWU

### PR DESCRIPTION
**Pull request by CedrikNikita**
missed in https://github.com/superhero-com/superhero-wallet/pull/3055,
fixes #3391

### CODE REVIEW

File: src/composables/transactionData.ts [hunk 1]
```diff
@@ -141,7 +141,7 @@ export function useTransactionData({
 
   const isDex = computed((): boolean => isTxDex(innerTx.value, dexContracts.value));
 
-  const isDexAllowance = computed((): boolean => (
+  const isAllowance = computed((): boolean => (
```
Comment (peronczyk) [inline src/composables/transactionData.ts:144]: If it's not related to dex I suggest to add some comment about what "allowance" actually is in this context.

**Review by peronczyk — APPROVED** [review]
