### PR TITLE
fix(ios): discover accounts for new wallet correctly

### LINKED ISSUE #2919: On iOS app when I create a new wallet I will get 2 AE accounts instead of 1
**Describe the bug**
On iOS app when I create a new wallet I will get 2 AE accounts instead of 1 

**To Reproduce**
1. Create new wallet
2. See that 2 ae acc will be added

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone13
 - Version 2.2.0 (2)

**Additional context**

https://github.com/superhero-com/superhero-wallet/assets/69896204/de3dcd0b-71e1-4a4b-988e-7095590c839a

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2919

### CODE REVIEW

File: src/popup/pages/Index.vue [hunk 1]
```diff
@@ -141,7 +141,10 @@ export default defineComponent({
 
     const termsAgreed = ref(false);
 
+    let isWalletNew = false;
```
Comment (CedrikNikita) [inline src/popup/pages/Index.vue:144]: Not very proud of this wording. Feel free to suggest new.

**Review by peronczyk — APPROVED** [review]
