### PR TITLE
fix: eth tx list not loading

### LINKED ISSUE #2889: ETH Tx are not visible from time to time on account-details page
**Describe the bug**
ETH Tx are not visible from time to time on account-details page, but they are visible on coin details page

**To Reproduce**
1. Go to acc details page

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS:macos
 - Browser chrome
 - Version123

**Additional context**

https://github.com/superhero-com/superhero-wallet/assets/69896204/964fafd0-e26d-4b92-b0da-0b02151e4cba

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2889

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
LGTM

**Comment by Liubov-crypto** [comment]
Now it's working. LGTM

I think space is needed here: 

eth space

Like here for example: 
eth det

File: src/protocols/ethereum/libs/EthplorerService.ts [hunk 1]
```diff
@@ -42,7 +42,7 @@ export class EthplorerService {
     // Without API key amount of calls are limited to two per every 1 second.
     // We're adding delays between calls to avoid getting empty results.
     // TODO: Use own node or paid version
-    if (!ETHPLORER_API_KEY) {
+    if (!ETHPLORER_API_KEY || ETHPLORER_API_KEY === 'freekey') {
```
Comment (CedrikNikita) [inline src/protocols/ethereum/libs/EthplorerService.ts:45]: What a mistake. :(
