### PR TITLE
fix: load old transactions

### LINKED ISSUE #2810: If the selected transaction type does not populate the transaction list, the user will not be able to load old transactions
filteredDexTransactions
fungibleTokenTransactions

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2810

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
LGTM

File: src/popup/components/TransactionList.vue [hunk 1]
```diff
@@ -203,7 +205,11 @@ export default defineComponent({
       }
     }
 
-    function checkLoadMore() {
+    async function checkLoadMore() {
+      // sleep is required because viewportElement scrollHeight
+      // is not being changed fast enough, after filter is applied
+      await sleep(50);
```
Comment (peronczyk) [inline src/popup/components/TransactionList.vue:211]: Maybe using `await nextTick()` would solve the issue and better fit into the Vue/DOM environment?

**Review by peronczyk — APPROVED** [review]
