### PR TITLE
fix: show correct details for pending ethereum transactions

### LINKED ISSUE #2789: ERC-20 Tx details are displaying wrong info
**Describe the bug**
ERC-20 Tx details are displaying wrong info

**To Reproduce**
1. Send ERC-20 
2. Click on Tx details when Tx is in pending status
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF
 - Version 122

**Additional context**
Reproducible on the current dev branch. 

Image

It should be: 

Image

### PR DESCRIPTION
**Pull request by martinkaintas**
fixed #2789 

Also removes timestamp and block number from pending transactions 
(`getBlock` will return a block even if `blockHash` is missing)

### CODE REVIEW

File: src/protocols/ethereum/views/TransactionDetails.vue [hunk 1]
```diff
@@ -136,6 +137,18 @@ export default defineComponent({
     );
 
     onMounted(async () => {
+      // If the transaction is a token transfer and it is still pending use the pending transaction
+      // because API wont be synced yet
+      // pendingTransaction will have the most accurate data at this point
+      if (accountsTransactionsPending.value[transactionOwner]) {
+        const pendingTransaction: ITransaction = accountsTransactionsPending.value[transactionOwner]
+          .find((tx) => tx.hash === hash) as ITransaction;
+        if (pendingTransaction && pendingTransaction.tx.contractId !== adapter.coinContractId) {
```
Comment (peronczyk) [inline src/protocols/ethereum/views/TransactionDetails.vue:146]:
```suggestion
        if (pendingTransaction?.tx?.contractId !== adapter.coinContractId) {
```

File: src/protocols/ethereum/views/TransactionDetails.vue [hunk 2]
```diff
@@ -136,6 +137,18 @@ export default defineComponent({
...
+          transaction.value = pendingTransaction;
+          return;
+        }
+      }
```
Comment (peronczyk) [inline src/protocols/ethereum/views/TransactionDetails.vue:150]: In my opinion this block of code is rather superfluous and I think using `return` within the `onMounted` callback is a bad practice. Consider this approach:

```suggestion
      const pendingTransaction = (accountsTransactionsPending.value[transactionOwner] || []).find((tx) => tx.hash === hash);
      if (pendingTransaction) {
        transaction.value = pendingTransaction;
      } else {
        // The logic of fetching the transaction data
```

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/protocols/ethereum/views/TransactionDetails.vue (hunk 2 above)
Comment (martinkaintas) [reply src/protocols/ethereum/views/TransactionDetails.vue:150]: `if (accountsTransactionsPending.value[transactionOwner])`
This statement is used to check if the pending transactions composable is initialized. Without it, if user refreshes on a tx details page he might get stuck loading.

Comment (martinkaintas) [reply src/protocols/ethereum/views/TransactionDetails.vue:150]: Also pending transactions do not have correct fee information, thus if the transaction isn't a contract call I think it makes sense to fetch the correct data from the node

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
