### PR TITLE
fix(aeternity): show all asset related transactions

### LINKED ISSUE #2918: Txs are not visible for LAEX token
**Describe the bug**
Txs are not visible for LAEX token.

**To Reproduce**
1. Go to LAEX coin details page
2. Check DEX tx list 
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser  chrome, safari
 - Version 123

**Additional context**

Image

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2918

### CODE REVIEW

File: src/protocols/aeternity/libs/AeternityAdapter.ts [hunk 1]
```diff
@@ -397,7 +397,10 @@ export class AeternityAdapter extends BaseProtocolAdapter {
           .filter(({ tx }) => !tx.contractId || tx.contractId === this.coinContractId);
       } else {
         regularTransactions = res.regularTransactions
-          .filter(({ tx }) => tx.contractId === assetContractId);
+          .filter(({ tx }) => (
+            tx.contractId === assetContractId
+            || JSON.stringify({ ...tx.arguments, ...tx.log }).search(assetContractId) !== -1
```
Comment (peronczyk) [inline src/protocols/aeternity/libs/AeternityAdapter.ts:402]: I suggest to use `includes` instead of `search` as search is slower and the result needs to be compared with `-1`.

**Review by peronczyk — APPROVED** [review]
