### PR TITLE
fix: show correct erc-20 transaction details

### LINKED ISSUE #2675: Transaction details page is showing wrong info for FT and ERC-20 tokens
**Describe the bug**
Transaction details page is showing wrong info for FT and ERC-20 tokens. It will show only fee but no amount that was sent. 

**To Reproduce**
1. Go to FT details page
2. Click on Tx details
3. Scroll down 

**Expected behavior**
Tx details page should shown total and fee amount

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser FF, Chrome
 - Version 122, 120

**Additional context**
Reproducible on ETH dev branch.

https://github.com/superhero-com/superhero-wallet/assets/69896204/5a8de581-19c2-4990-8d9e-6cdd7f193f0c

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2675

### CODE REVIEW

File: src/protocols/ethereum/libs/EtherscanService.ts [hunk 1]
```diff
@@ -112,6 +116,19 @@ export class EtherscanService {
     ) || [];
   }
 
+  async fetchAccountTokenTransactionByHash(
+    hash: string,
+    address: string,
+    blockNumber: string,
+  ): Promise<ITransaction> {
+    // Not the best solution, but it seems to be the only way to get token transaction details
```
Comment (CedrikNikita) [inline src/protocols/ethereum/libs/EtherscanService.ts:124]: We can use ethplorer, to fetch this info.
https://sepolia-api.ethplorer.io/getTxInfo/0x03cc5ebf3001fc8dce167ffcbc10896aed4c7dad10996e4d652ac50c6f4f2559?apiKey=freekey

Comment (martinkaintas) [reply src/protocols/ethereum/libs/EtherscanService.ts:124]: Ethplorer's response is missing fields like `gasPrice` and `nonce`

**Comment by CedrikNikita** [comment]
> Doesn't seems right? 

Also the amount is being converted to a fiat like it has Ethereum value.

File: src/protocols/ethereum/libs/EtherscanService.ts [hunk 2]
```diff
@@ -94,12 +95,16 @@ export class EtherscanService {
...
       assetContractId?: AssetContractId;
+      startblock?: string;
+      endblock?: string;
     } = {},
   ): Promise<ITransaction[]> {
     const {
       assetContractId,
       page = '1',
       offset = TXS_PER_PAGE.toString(),
+      startblock = '0',
```
Comment (CedrikNikita) [inline src/protocols/ethereum/libs/EtherscanService.ts:106]: No need to add `startblock` and `endblock` here.

**Review by CedrikNikita — CHANGES_REQUESTED** [review]
ethereum transactions
All the received transactions are now marked as sent.

File: src/protocols/ethereum/libs/EtherscanService.ts (hunk 2 above)
Comment (CedrikNikita) [reply src/protocols/ethereum/libs/EtherscanService.ts:106]: The comment is about list of all transactions. No need to specify `startblock` and `enblock` there.

File: src/composables/fungibleTokens.ts [hunk 3]
```diff
@@ -190,6 +191,9 @@ export function useFungibleTokens() {
         assetContractId = contractCallData.token;
       }
     }
+    if (protocol === PROTOCOLS.ethereum) {
+      assetContractId = toEthChecksumAddress(assetContractId);
+    }
```
Comment (peronczyk) [inline src/composables/fungibleTokens.ts:196]: I strongly suggest to avoid doing any protocol specific logic in common files. Maybe the asset contract ID could be converted on the service level (in the function that normalizes the API response into our interfaces)?

File: src/popup/components/Tokens.vue [hunk 4]
```diff
@@ -102,8 +103,12 @@ export default defineComponent({
     }
 
     function getTokenPlaceholderUrl(token: ITokenResolved) {
+      let { contractId } = token;
+      if (token.protocol === PROTOCOLS.ethereum) {
+        contractId = toEthChecksumAddress(token.contractId!);
+      }
```
Comment (peronczyk) [inline src/popup/components/Tokens.vue:109]: IDEM

File: src/protocols/ethereum/helpers/index.ts [hunk 5]
```diff
@@ -47,3 +50,13 @@ export function normalizeWeb3EthTransactionStructure(
...
 }
+
+/**
+ * Convert address to checksum address if is prefixed with 0x
+ * to avoid erros in cases like contractId="ethereum"
+ */
+export function toEthChecksumAddress(address: string) {
+  if (!address) return address;
+  if (address.startsWith('0x')) return toChecksumAddress(address);
+  return address;
```
Comment (peronczyk) [inline src/protocols/ethereum/helpers/index.ts:61]:
```suggestion
  return (address?.startsWith('0x')) ? toChecksumAddress(address) : address;
```

File: src/protocols/ethereum/libs/EthereumAdapter.ts [hunk 6]
```diff
@@ -318,11 +318,25 @@ export class EthereumAdapter extends BaseProtocolAdapter {
...
   }
 
-  override async fetchTransactionByHash(hash: string) {
+  override async fetchTransactionByHash(hash: string, transactionOwner?: AccountAddress) {
     const web3Eth = this.getWeb3EthInstance();
     const transaction = await getTransaction(web3Eth, hash, DEFAULT_RETURN_FORMAT);
+
+    // If the transaction is a token transfer, fetch the token transaction using the etherscan API
+    // Because the web3 library does not give enough information about token transactions
+    if (transaction?.input && transaction.input !== '0x' && transaction.blockNumber) {
```
Comment (peronczyk) [inline src/protocols/ethereum/libs/EthereumAdapter.ts:327]:
```suggestion
    if (transaction?.input !== '0x' && transaction.blockNumber) {
```

File: src/protocols/ethereum/views/TransactionDetails.vue [hunk 7]
```diff
@@ -77,16 +107,23 @@ export default defineComponent({
         : TX_DIRECTION.received,
     );
 
+    const isEthTransaction = computed(
```
Comment (peronczyk) [inline src/protocols/ethereum/views/TransactionDetails.vue:110]: We know this is an Ethereum transaction because this component is an ethereum specific component. Did you mean `isCoin` or something?

**Review by peronczyk — CHANGES_REQUESTED** [review]

File: src/protocols/ethereum/views/TransactionDetails.vue (hunk 7 above)
Comment (martinkaintas) [reply src/protocols/ethereum/views/TransactionDetails.vue:110]: I meant, `isEth` as in is ETH the symbol and not short for Ethereum
But it is indeed confusing so I'll change this

File: src/composables/fungibleTokens.ts (hunk 3 above)
Comment (martinkaintas) [reply src/composables/fungibleTokens.ts:196]: I've created a new task for this #2725 as this requires us to change this in many places

**Comment by Liubov-crypto** [comment]
It shows me correct Tx details for ETH transaction. But I was not able to send ERC-20 tokens (they are not visible in my wallet for some reason). 
I think I have to retest it cuz the last commit has been fault.

**Comment by Liubov-crypto** [comment]
LGTM

File: src/protocols/ethereum/views/TransactionDetails.vue [hunk 8]
```diff
@@ -77,16 +107,23 @@ export default defineComponent({
         : TX_DIRECTION.received,
     );
 
+    const isTransactionCoin = computed(
+      // TODO replace with proper check when types are unified/updated
+      () => transaction.value?.tx?.type === 'SpendTx',
```
Comment (peronczyk) [inline src/protocols/ethereum/views/TransactionDetails.vue:112]: Why not `isCoin` taken from `utils/common`?

**Review by peronczyk — APPROVED** [review]
