### PR TITLE
fix: show correct icons & amount on tx details

### LINKED ISSUE #2579: ETH / BTC icon is displaying wrong in Tx details page
**Describe the bug**
ETH / BTC icon is displaying wrong in Tx details page

**To Reproduce**
1. Open Tx details page
2. Check ETH / BTC icon 
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser FF
 - Version 119

**Additional context**
Reproducible on ETH dev branch.

Image

Image

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2579

### CODE REVIEW

File: src/popup/components/TransactionTokenRows.vue [hunk 1]
```diff
@@ -82,11 +82,19 @@ export default defineComponent({
 
     const getTokenName = (token: ITokenResolved) => token?.isAe ? AE_SYMBOL : token.symbol;
 
+    const amountFormatted = ({ token, isRounded }: {token: ITokenResolved; isRounded: boolean}) => {
+      // if amount is in scientific notation it is not rounded
+      if (token.amount && (!isRounded || token.amount?.toString().indexOf('e') !== -1)) {
```
Comment (CedrikNikita) [inline src/popup/components/TransactionTokenRows.vue:87]: Why this condition is needed? What was the case?

Comment (martinkaintas) [reply src/popup/components/TransactionTokenRows.vue:87]: BTC amount was shown in scientific notation

**Review by peronczyk — APPROVED** [review]

**Comment by Liubov-crypto** [comment]
LGTM
