### PR TITLE
fix(aeternity): format recipient address correctly

### LINKED ISSUE #2801: Contract address and name hash are no longer formatted in `TransactionDetails`

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2801

### CODE REVIEW

File: src/protocols/BaseProtocolAdapter.ts [hunk 1]
```diff
@@ -79,6 +79,14 @@ export abstract class BaseProtocolAdapter {
    */
   abstract isAccountAddressValid(address: AccountAddress, networkType?: NetworkType): boolean;
 
+    /**
+   * Validates if the hash address matches the protocol.
```
Comment (martinkaintas) [inline src/protocols/BaseProtocolAdapter.ts:83]: small indentation issue
