### PR TITLE
fix: do not call cordova mnemonic migration on extension

### LINKED ISSUE #2713: Background page synchronization bug
**On develop**
It seems that background page unaware of the current mnemonic (or maybe the whole state). This results in popup being unauthorized, and trying to authorize itself. 
extension Synchonization bug

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2713 
Even though the actual migration was not being called because of the inner if check, it was still causing issues with the extension

### CODE REVIEW

**Review by CedrikNikita — APPROVED** [review]

File: src/composables/accounts.ts [hunk 1]
```diff
@@ -39,7 +40,7 @@ const mnemonic = useStorageRef<string>(
   STORAGE_KEYS.mnemonic,
   {
     backgroundSync: true,
-    migrations: RUNNING_IN_TESTS ? [
+    migrations: RUNNING_IN_TESTS || IS_EXTENSION ? [
```
Comment (peronczyk) [inline src/composables/accounts.ts:43]: It's OK, but what do you think about making the 2 arrays as 1 (less quirky way)? I mean instead choosing between 2 arrays that has some duplicated items just:

```
    migrations: [
      migrateMnemonicVuexToComposable,
      (!RUNNING_IN_TESTS && !IS_EXTENSION) && migrateMnemonicCordovaToIonic,
    ].filter(excludeFalsy),
```

**Review by peronczyk — APPROVED** [review]

File: src/composables/accounts.ts [hunk 2]
```diff
@@ -39,11 +40,9 @@ const mnemonic = useStorageRef<string>(
   STORAGE_KEYS.mnemonic,
   {
     backgroundSync: true,
-    migrations: RUNNING_IN_TESTS ? [
-      migrateMnemonicVuexToComposable,
-    ] : [
+    migrations: [
+      ...(!(RUNNING_IN_TESTS || IS_EXTENSION) ? [migrateMnemonicCordovaToIonic] : []),
```
Comment (CedrikNikita) [inline src/composables/accounts.ts:44]: I think it is suppose to be run only on previously Cordova based platforms.

**Review by CedrikNikita — CHANGES_REQUESTED** [review]
This code is not working for an reverse iframe scenario.

**Comment by martinkaintas** [comment]
> It's working in Chrome but doesn't work in FF:

You need to allow the extension to run on the DEX

**Review by CedrikNikita — APPROVED** [review]
