### PR TITLE
fix: reset input after generating gift card

### LINKED ISSUE #2999: After creating a gift card, amount field error appears
**Describe the bug**
After user is generating a gift card and it is shown on bottom. Under the gift card amount field will appear "This field must be more than 0" error message

**To Reproduce**
1. Go to more
2. Click on Gift Card
3. Enter amount
4. Select generate gift card

**Expected behavior**
Amount field error msg should appear

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: windows
 - Browser brave
 - Version 1.65.114 Chromium: 124.0.6367.60]

**Additional context**

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2999

### CODE REVIEW

File: src/popup/pages/Invite.vue [hunk 1]
```diff
@@ -143,7 +143,7 @@ export default defineComponent({
       }
 
       addInvite(Buffer.from(secretKey, 'hex').slice(0, 32));
-      formModel.value.amount = '';
+      resetField();
```
Comment (peronczyk) [inline src/popup/pages/Invite.vue:146]: Why not just setting the `formModel.amount` to null / `''` ?

Comment (martinkaintas) [reply src/popup/pages/Invite.vue:146]: Because the field is dirty and will show an error. Resetting it cleans it

**Review by peronczyk — APPROVED** [review]
