### PR TITLE
fix: missing payload from multisig tx

### LINKED ISSUE #2635: Payload is absent in Multisig Tx details page
https://aeternity-blockchain.atlassian.net/browse/SW-1013

Describe the bug

Payload is absent in Multisig Tx details page. Currently it’s visible only in ae scan page. 

Expected result

If user added some info to payload field it should be present in Multisig Tx details page.

Steps to reproduce
1. Propose multisig Tx
2. Add payload info and send Tx

3. Check Tx details 

Environment selector

Extension
Firefox
MacOS
Web wallet

**Comment**

Liubov Sharga 
October 2, 2023 at 2:46 PM

For some reason this fix doesn’t work on the release branch. The changes were not applied. 

Liubov Sharga 
August 14, 2023 at 9:53 AM

@Paweł Stachel Rechecked, now the account discovery is working, but from time to time. It takes some time for the wallet to load the information.

Liubov Sharga 
August 9, 2023 at 2:37 PM

The payload issue has been fixed. 

But I found that account discovery is broken in extension: 

Image
Image
https://github.com/superhero-com/superhero-wallet/assets/147718725/080a5862-45a7-4e4f-a86d-f2f463cfb0d9

### PR DESCRIPTION
**Pull request by martinkaintas**
closes #2635

### CODE REVIEW

**Comment by Liubov-crypto** [comment]
Fixed, LGTM

File: src/protocols/aeternity/helpers/index.ts [hunk 1]
```diff
@@ -209,9 +210,14 @@ export function getTransaction(transaction: ICommonTransaction): ITransaction |
 }
 
 export function getTransactionPayload(transaction: ITransaction) {
-  return (transaction.tx?.payload)
-    ? decode(transaction.tx?.payload).toString()
-    : null;
+  if (transaction.tx?.payload) {
```
Comment (CedrikNikita) [inline src/protocols/aeternity/helpers/index.ts:213]: We can use `getInnerTransaction` instead of two `if`s.

File: src/popup/pages/MultisigProposalDetails.vue [hunk 2]
```diff
@@ -604,7 +604,7 @@ export default defineComponent({
 
   .content {
     background-color: variables.$color-bg-4;
-    padding-bottom: 120px;
+    padding-bottom: 12px;
```
Comment (CedrikNikita) [inline src/popup/pages/MultisigProposalDetails.vue:607]: The transaction info will look like that after your changes.
image
instead of this
image

**Review by CedrikNikita — CHANGES_REQUESTED** [review]

File: src/popup/pages/MultisigProposalDetails.vue (hunk 2 above)
Comment (martinkaintas) [reply src/popup/pages/MultisigProposalDetails.vue:607]: On my screen it looked like a mistake, as there was a huge gap at the bottom of the page. I will revert this as it is unrelated anyway

**Review by CedrikNikita — APPROVED** [review]
