### PR TITLE
fix: be able to migrate mnemonic from vuex

### LINKED ISSUE #2960: Issue when upgrading extension from 2.1.6 to latest Release. Seed is not kept
Reported by philip

_Uhm I just updated my Superhero Wallet on Firefox from 2.1.6 to the latest version and need to re-enter my seed, this seems really bad..._

### PR DESCRIPTION
**Pull request by CedrikNikita**
fixes #2960

### CODE REVIEW

**Review by peronczyk — APPROVED** [review]

**Review by peronczyk — APPROVED** [review]

File: src/popup/components/Modals/ResetWalletModal.vue [hunk 1]
```diff
@@ -77,6 +77,9 @@ export default defineComponent({
       disconnectDapps();
 
       await WalletStorage.clear();
+      // TODO: Rethink this approach
+      // It is removing the remaining vuex state
+      await browser.storage.local.clear();
```
Comment (peronczyk) [inline src/popup/components/Modals/ResetWalletModal.vue:82]: Maybe we could add this in next release when we will be 100% ready that the migrations works fine?

Comment (CedrikNikita) [reply src/popup/components/Modals/ResetWalletModal.vue:82]: The user won't be able to reset the wallet without it.

Comment (peronczyk) [reply src/popup/components/Modals/ResetWalletModal.vue:82]: You're right. So let's leave it.

**Review by smaroudasunicorn — APPROVED** [review]
